### ISSUE TITLE
Not launching on macOS due to allthetweaks

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [AllTheMods/All-the-mods-7-Sky#105]
Error: Failure message: All The Tweaks (allthetweaks) encountered an error during the common_setup event phase
		java.lang.IllegalStateException: Rendersystem called from wrong thread

When I remove 'allthetweaks-1.9.9a-1.18.2-40.1.60.jar' the game launches perfectly fine. 
Pastebin crashlog: https://pastebin.com/w51jArmq

**Comment by thevortex** [comment]
https://www.curseforge.com/minecraft/mc-mods/all-the-tweaks/files/3960407 can i get you to try launching with this version and let me know if it fixes it?

**Comment by madhandennis** [comment]
Having the same issue. Tried to install the version linked above with no effect, game still crashes with the same Rendersystem error even with allthetweaks-1.9.9c-1.18.2-40.1.60.jar

**Comment by madhandennis** [comment]
@MathiasDeWeerdt I decided to give ATM7-Sky another shot and read an old issue by someone saying they just removed allthetweaks. Tried it and it works fine on my M1! allthetweaks seems to just add on custom loading background, etc. So mostly cosmetics. Doesn't seem to affect the gameplay so far.

**Comment by thevortex** [comment]
it will actually cause issues for things in the pack @madhandennis a fix is coming for this later today

**Comment by thevortex** [comment]
the fix is live. v 1.9.9.6 should fix things up, sorry for the delays here

**Comment by madhandennis** [comment]
Thanks @thevortex ! Works wonderfully! I was able to make it work after adding in 1.9.9.6 of allthetweaks. Thanks for the fix.

Side note: Looks like the pack on Curseforge isn't referencing 1.9.9.6. So on a fresh install, it still uses the old version with the issue. FYI

**Comment by thevortex** [comment]
there is an update coming for the main pack soon
