### ISSUE TITLE
RFTools crafter is consuming durability on eternal ore hammer

### ISSUE THREAD

**Issue by TristonWasik** [AllTheMods/All-the-mods-7-Sky#106]
Ore hammers that are given the Eternal upgrade from forbidden and arcanus still use durability in rftools crafter.

![image](https://user-images.githubusercontent.com/32952542/186550810-13d34731-411f-4a7e-a488-8cc0c6a18d76.png)

**Comment by enigmaquip** [comment]
ore hammers are blacklisted from being smithed with the eternal stella, they don't work with eternal and there is not plan for them to

**Comment by TristonWasik** [comment]
ah, well the recipe works inside of the smithy and uses up the eternal stella. good to know though, thanks

**Comment by enigmaquip** [comment]
Sorry, didn't realize we had missed it in the earlier releases, the recipe removal was very recent. But yeah we removed it because they don't interact properly together.
