### ISSUE TITLE
[1.0.3] Flux Hammer voids items

### ISSUE THREAD

**Issue by sreny1** [AllTheMods/All-the-mods-7-Sky#108]
When using Flux Hammer for 'Sand Block 1x' to get Dust it seems to hammer as many items as there is space in the output inventory.
This is ignoring the fact that you get 9 Dust per compressed Sand - Essentially voiding up to 8/9th or the items when hammering compressed Sand

Steps to recreate:
1: Use Flux Hammer with Compressed Sand with a Netherite Upgrade
2: have an export inventory with space for 64 Dust
3: Watch the Flux Hammer use up 64 'Sand Block 1x' when it really should use up 7 to get 63 Dust or 8 to get 64 Dust to fill up the output inventory.

This issue happend with a Flux Hammer and with a Drawer as output inventory

**Comment by enigmaquip** [comment]
Fixed in Ex Machinis
