### ISSUE TITLE
[Suggestion] Remove Certus Quartz Seeds from Ex Nihilo Sieving Droptable

### ISSUE THREAD

**Issue by TheonlyTazz** [AllTheMods/All-the-mods-7-Sky#111]
### Reason for Suggestion

Certus Quartz Seeds cannot be stacked, thus troublesome for average players to store them/work out a proper overflow system.
increasingly troublesome is the fact that Certus Quartz Seeds dont despawn either, meaning they accumulate over time.
After running an ATM7Sky server for less than a week, we already had our server come to 2 massive deadlocks, because of over 230k items.

Additionally, Certus Quartz Seeds can be crafted with Sand and Certus Quartz Dust, which you at that point both should be having already.

![grafik](https://user-images.githubusercontent.com/3908847/186951449-103fe512-6ca6-4253-9dfc-18b9bd48019b.png)

after using `/kill @e[type=item]`  the whole area got spammed with packet issues
![grafik](https://i.imgur.com/MpksS9l.gif)

### Solution that i currently have implemented on the server:
kubejs/data/exnihiloae/recipes/sieve/ens_certus_seed.json:
```js
{"type":"exnihilosequentia:sieve","rolls":[{"chance":0.0,"mesh":"string"}],
    "input":{"item":"exnihiloae:crushed_skystone"},
    "result":{"item":"ae2:certus_quartz_crystal"}}```

**Comment by enigmaquip** [comment]
Removed in 1.0.4
