### ISSUE TITLE
No recipe for Thermal series compost

### ISSUE THREAD

**Issue by clarketronics** [AllTheMods/All-the-mods-7-Sky#113]
Thermal series compost is used to make podzol and mycelium but has no recipe 
![image](https://user-images.githubusercontent.com/38007037/186998567-33872232-7ca0-49b1-aac8-b711cafa4ea6.png)

**Comment by enigmaquip** [comment]
While it has no special jei tab for it, thermal's compost it made by thermal's batch composter
