### ISSUE TITLE
1.0.3 Ex Nihilo Unreliable

### ISSUE THREAD

**Issue by Teebor** [AllTheMods/All-the-mods-7-Sky#114]
fresh install of 1.0.3 via Curseforge

<SYMPTOMS>
Can craft hammer, crook etc however they do not work as intended

Crook does not give any silkworm drops after testing on 10+ trees

Hammer doesn't function correctly and only returns the blocks placed, Cobble doesn't return Gravel, Gravel doesn't return Sand, and Sand doesn't return Dust

<WORKAROUND>
Restart the client 3-4 times before everything worked as expected

Might be a mod incompatibility issue/loading order issue ?

**Comment by jeremiahwinsley** [comment]
This is a Forge bug which leads to recipes occasionally not loading, they are working on a patch for it. _Usually_ this is a very rare bug which goes away after one restart so I think you just got unlucky?

**Comment by jeremiahwinsley** [comment]
Update, this is fixed in Forge 40.1.74, which should be in the next pack update.
