### ISSUE TITLE
Drawers loose locked status when carried

### ISSUE THREAD

**Issue by clarketronics** [AllTheMods/All-the-mods-7-Sky#115]
1. Put anything in a 1x1 drawer
2. Use config tool to lock
3. Pick up using carrier
4. Place block back down

The lock has gone, I dont propose blacklisting from carrier as its incredible useful. Maybe something can be done config side if not will raise issue with mod provider.

**Comment by TiphaineLAURENT** [comment]
I think it is intended from the mod author since simply break them does the same thing

**Comment by enigmaquip** [comment]
Fixed in Functional Storage-1.18.2-1.0.6
