### ISSUE TITLE
Exnihilo Crucible died

### ISSUE THREAD

**Issue by OceanRift** [AllTheMods/All-the-mods-7-Sky#120]
After the update to 1.04 the crucible farm is dead, and no recipes, how to fix it?

**Comment by PieIsAwesome7102** [comment]
Does the fired crucible turn into an unfired crucible when you place it?

**Comment by Wazzzer** [comment]
> Does the fired crucible turn into an unfired crucible when you place it?

i'm the same it doesn't work for me. also the sieves are water logged as well as the slab crafting tables

**Comment by Mitchell5200** [comment]
> > Does the fired crucible turn into an unfired crucible when you place it?
> 
> i'm the same it doesn't work for me. also the sieves are water logged as well as the slab crafting tables

If you're on a server, ensure you are on the same pack version as the server

**Comment by Mitchell5200** [comment]
Closing.
