### ISSUE TITLE
Sieves stopped working

### ISSUE THREAD

**Issue by alwynbarnard** [AllTheMods/All-the-mods-7-Sky#123]
After the last update (+-9 hours ago) my sieves and auto sieves no longer sieve anything. Tried with dirt, sand, dust and gravel

**Comment by alwynbarnard** [comment]
I suspect my world is corrupted. Many items stopped working

**Comment by e30Birdy** [comment]
Mine did the same and a full close of the game and reopen fixed that, happened twice now
