### ISSUE TITLE
MC crashes when I hover in my backpack inventory

### ISSUE THREAD

**Issue by Riiikku** [AllTheMods/All-the-mods-7-Sky#128]
hey guys,
I am playing with friends on a server with mods. ATM 7 to the sky to be specific.
We already are playing for 2 weeks so far but since yesterday, I always get Exit Crash -1. It´s probably triggered through my backpack.
when I open the backpack and hover with my courser in it, it soon crashes. I tried to reinstall java, minecraft and curseforge but with no success. Would appreciate any help :)

we are currently playing on 1.0.2 version.

[crash-2022-08-29_13.53.40-client.txt](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9444402/crash-2022-08-29_13.53.40-client.txt)

**Comment by enigmaquip** [comment]
This was an issue with a specific version of Apotheosis, updating your pack to the current version (v1.0.4) fixes this
