### ISSUE TITLE
builder quarry and digital miner not working in the other

### ISSUE THREAD

**Issue by Schrimpes** [AllTheMods/All-the-mods-7-Sky#129]
the digital miner and the quarry do not work in the "the other" dimension. in "end" and "twilight forest" they work without problems.
the quarry says "break was canceled" and the miner turns on, shows the blocks to be mined and then turns off again.

**Comment by Mitchell5200** [comment]
Intended game mechanic, in both 7 and 7sky you cannot machine quarry the other, only hand mining by a player is permitted
