### ISSUE TITLE
Various metals can no longer be cast into ingots in the tinkers smeltery

### ISSUE THREAD

**Issue by Schrimpes** [AllTheMods/All-the-mods-7-Sky#130]
is it intentional that in the current version, 1.0.4,  you can no longer cast different metals from the smeltery into ingots. for example silver, nickel, lead, elektrum etc. nuggets can be casted.

**Comment by Schrimpes** [comment]
I don't know how or why, but now the ingot casting works again.

**Comment by uberfuzzy** [comment]
Seems to be broken again, `sky-1.0.9`  with `TConstruct-1.18.2-3.5.2.40.jar`

was working a few days ago with 1.0.8

**Comment by Mitchell5200** [comment]
Tested in 1.1.4, Confirmed working, Closing
