### ISSUE TITLE
No way to get a sponge (Elder Guardian)

### ISSUE THREAD

**Issue by kleintra** [AllTheMods/All-the-mods-7-Sky#134]
The only way I see to get a sponge is the Elder Guardian Prediction.  Is there another way?  BTW, there doesn't seem to be a way to spawn an Elder Guardian.

**Comment by AWDoBaun** [comment]
There is the "Spirit" mod "Soul Pedestal" that can convert a guardian spirit to an elder guardian monster, that can then be captured, swabbed, killed, etc.

**Comment by Mitchell5200** [comment]
Another method is Alchemsitry, Closing
