### ISSUE TITLE
All the Ores Thermal alloy missing induction smelt recipe 

### ISSUE THREAD

**Issue by AlphaP2712** [AllTheMods/All-the-mods-7-Sky#136]
and Thermal alloy original hide form JEI 
![image](https://user-images.githubusercontent.com/74948675/187986536-66da4e52-349e-4d1f-959e-a6e702ca1c36.png)
![image](https://user-images.githubusercontent.com/74948675/187986601-b36c36a3-4736-4a3c-9be7-583e581e959b.png)

**Comment by KamiAso** [comment]
for some reason induction smelter only accepts blocks instead of ingots

**Comment by AlphaP2712** [comment]
maybe because they still have thermal original alloy version with same ore dict? 
![image](https://user-images.githubusercontent.com/74948675/188070678-90c9772d-15b2-4d6a-b250-7dd71083014c.png)

**Comment by Mitchell5200** [comment]
Confirmed working in 1.1.4, Closing
