### ISSUE TITLE
[1.0.4] Dup with Create and FTBChunks

### ISSUE THREAD

**Issue by KamiAso** [AllTheMods/All-the-mods-7-Sky#137]
1. Use a create wrench to break any create blocks in a chunk that one doesnt have permission to break blocks
2. The item will go into player's inventory due to how create wrench works (input into inventory instead of dropping)
3. The block wont be broke but the block will also appear in the player's inventory

**Comment by oly2o6** [comment]
Mod issue, closing to keep eyes off of it incase everyone has already made the jump to 1.19
 (also with sb3 out and using alot of create, i assume this would be fixed by now)
