### ISSUE TITLE
[1.0.4] Game crashes on startup

### ISSUE THREAD

**Issue by CoziiFrog** [AllTheMods/All-the-mods-7-Sky#142]
My game crashes on startup running version 1.0.4

This is the message I am given:

The game crashed whilst initializing game
Error: java.lang.IllegalAccessError: Update to static final field net.minecraft.client.gui.screens.TitleScreen.f_96716_ attempted from a different method (handler$zci000$packmenu_init) than the initializer method <clinit> 

I have also attached the crash log below

[crash-2022-09-03_14.39.57-client.txt](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9482690/crash-2022-09-03_14.39.57-client.txt)

**Comment by CoziiFrog** [comment]
I seem to have fixed this issue... Although 8GB of ram is allocated to Minecraft through the curseforge settings, I set the Memory settings in profile options to 8GB instead of "Use System Memory Settings" and it now loads... Silly computers.

![image](https://user-images.githubusercontent.com/81523475/188273552-b653dcd9-809c-4f0d-b3c1-3b564bbf2dad.png)

**Comment by enigmaquip** [comment]
Silly curseforge launcher. Thanks for coming back and commenting
