### ISSUE TITLE
Applied energistics import bus and transport system not working after connecting to mob farm 

### ISSUE THREAD

**Issue by Suicidalpandahug** [AllTheMods/All-the-mods-7-Sky#146]
I have an automated sieving system, compacting system and smelting system for all my ores and other resources. All be it a complex system of cables, pipes and import buses i have gone over my system at least 5 times to make sure there are no hiccups or problems with it and so I decided to ask about it here. 

Any quick solve for it? i really wanna move forward with my playthrough but cant without my AE systems working.

PS: The system crash includes the wireless crafting system not being accessible even with all range boosters and while being right beside my ME system.

**Comment by jeremiahwinsley** [comment]
System might just be running out of power? Have you tried adding power cells to the system? Make sure you don't have multiple controllers connected to each other too

**Comment by Suicidalpandahug** [comment]
@jeremiahwinsley is there a solution you might suggest me to try so we can get the ball rolling on solving the issue? I wanna help in whatever way i can.

**Comment by Mitchell5200** [comment]
> @jeremiahwinsley is there a solution you might suggest me to try so we can get the ball rolling on solving the issue? I wanna help in whatever way i can.

Are your storage cells full, coz that might be an issue, otherwise a few screenshots might be able to help us help you

**Comment by Suicidalpandahug** [comment]
i have 2 disk storage thingys completely filled with 256k storage disks so i doubt they are full. what screenshots would you like ? the actual cable systems and what they are connected to ?

**Comment by Suicidalpandahug** [comment]
well suffice it to say, i just lost all of my progress. files got corrupt and lost everything so whether a solution was found or not doesnt matter anymore.

**Comment by jeremiahwinsley** [comment]
For the power thing - I didn't mean you didn't have enough power outside the system, I meant the system itself might be running out of power. The controller has a limited buffer size for power. That is refilled every so often, and then your system uses power out of the buffer. If your system uses more power than you have room in the buffer for, then it just shuts off. That's where the energy cells come in, they increase the buffer size.

What do you mean by corrupt files? Is it corrupt configs (which can be fixed) or did the world itself get corrupted?

**Comment by Suicidalpandahug** [comment]
I think i messed around with the files and ended up deleting the whe
instance while moving some files around. So I guess I'll start over. Thanks
for the help
