### ISSUE TITLE
Sight Potions not working.

### ISSUE THREAD

**Issue by LordHarkon** [AllTheMods/All-the-mods-7-Sky#150]
None of the sight potions work. I have tried coal and allthemodium, both potions and charm, and the ores are not highlighted.

**Comment by monokin1114** [comment]
Are you using shaders? As it doesnt work with shaders.

**Comment by Suicidalpandahug** [comment]
> None of the sight potions work. I have tried coal and allthemodium, both potions and charm, and the ores are not highlighted.

well the sight potions and charms have a range so you still need to be relatively close to the ores to get the effect of seeing the highlight.

**Comment by LordHarkon** [comment]
> Are you using shaders? As it doesnt work with shaders.

I am not using any shaders. I think I tried adding optifine and it crashed, so I can't use shaders even if I wanted.


> > None of the sight potions work. I have tried coal and allthemodium, both potions and charm, and the ores are not highlighted.
> 
> well the sight potions and charms have a range so you still need to be relatively close to the ores to get the effect of seeing the highlight.

I was right on top of it. I assume it should highlight the ore even if it was discovered.

**Comment by FunkyMoneyMan** [comment]
Yep not working for me either. The modpack doesn't have shaders enabled by default so this issue comes with the modpack as is. Hopefully this is fixed soon!

**Comment by jbullen1** [comment]
I'm also having the same issue.  I haven't made any changes to the pack and don't use shadders.

**Comment by gtokarz** [comment]
same here no shaders

**Comment by LordHarkon** [comment]
The mod seem to work fine, albeit with quite a short range, when on a server. I have transfered my world to a server I own and the potions and charms for ores seem to suddenly work. I have only tried with allthemodium and unobtanium, but the rest should work as well. Maybe something can be done to increase their range? Cause it seems to be quite small in my opinion.

**Comment by FunkyMoneyMan** [comment]
I play on the server and the potion doesn't work. I have gotten right up next to the ore and it doesn't highlight like I see in videos. Have you changes any settings in your config file?

> The mod seem to work fine, albeit with quite a short range, when on a server. I have transfered my world to a server I own and the potions and charms for ores seem to suddenly work. I have only tried with allthemodium and unobtanium, but the rest should work as well. Maybe something can be done to increase their range? Cause it seems to be quite small in my opinion.

**Comment by LordHarkon** [comment]
> I play on the server and the potion doesn't work. I have gotten right up next to the ore and it doesn't highlight like I see in videos. Have you changes any settings in your config file?
> 
> > The mod seem to work fine, albeit with quite a short range, when on a server. I have transfered my world to a server I own and the potions and charms for ores seem to suddenly work. I have only tried with allthemodium and unobtanium, but the rest should work as well. Maybe something can be done to increase their range? Cause it seems to be quite small in my opinion.

I have not changed anything. Just downloaded de server, put my world, and started it.

**Comment by FunkyMoneyMan** [comment]
Well then I hope this is something the pack devs look into. Since I know plenty of people who also have this issue. I assume it's since they have so many mods that something is conflicting somewhere. Too bad there is no sure/easy way to fix it. Especially since progression is kinda relying on these potions to find the ores.
> > I play on the server and the potion doesn't work. I have gotten right up next to the ore and it doesn't highlight like I see in videos. Have you changes any settings in your config file?
> 
> > 
> 
> > > The mod seem to work fine, albeit with quite a short range, when on a server. I have transfered my world to a server I own and the potions and charms for ores seem to suddenly work. I have only tried with allthemodium and unobtanium, but the rest should work as well. Maybe something can be done to increase their range? Cause it seems to be quite small in my opinion.
> 
> 
> 
> I have not changed anything. Just downloaded de server, put my world, and started it.

**Comment by DalHowHug** [comment]
I am also experiencing the same issue. No shaders used either

**Comment by BanzaiRun** [comment]
1.0.7

I did think I "was" having this issue until I moved to a new hill and all was fine. Perhaps all the atm ore had been mined in the first hill /s hth

**Comment by gtokarz** [comment]
For me it is working randomly at this moment, trying to catch any error logs when that happens, I have seen some GL errors in the log, but I am not sure if it is 100% related to sight potions

**Comment by Dudderle** [comment]
Same issue here

**Comment by Mitchell5200** [comment]
Ore sight Potions have been sometimes hit or miss, Tested working in 1.1.4 , Closing unless other issues are reported on the newest versions
