### ISSUE TITLE
Quest log missing something or typo ???

### ISSUE THREAD

**Issue by DiggityMan420** [AllTheMods/All-the-mods-7-Sky#151]
open the quest log > main quest part 2 > blaze rods It says can be used with silent gear (no Silent Gear mod) see [pic](https://ibb.co/fCksGj5)

![Screenshot_25](https://user-images.githubusercontent.com/45196448/188791981-fcac5df2-0df9-4189-9d7f-7fcd3594a707.jpg)

**Comment by enigmaquip** [comment]
Fixed in 1.0.9
