### ISSUE TITLE
Seed (mystical agriculture) dropping when harvested

### ISSUE THREAD

**Issue by Moutronn78** [AllTheMods/All-the-mods-7-Sky#153]
When I harvest some inferium, I don't get the seed, wich I think is normal on this modpack, but, when I keep right click on a seed with a whatering can, I get the seed.
![2022-09-07_23 03 02](https://user-images.githubusercontent.com/113065465/188979060-10f99bc7-4b61-4e93-a378-93a5930069dd.png)

**Comment by Mitchell5200** [comment]
Seeds have a low chance of dropping sometimes. Closing
