### ISSUE TITLE
achievements didn't save 

### ISSUE THREAD

**Issue by Dude919** [AllTheMods/All-the-mods-7-Sky#154]
I was playing on a newly created world and finished the **getting started** achievements page in the quest book and then saved and quit the game.

Next time I loaded my saved world, I found nothing of my achievements done like I didn't get any of them.

Any one else encoutered the same issue ? and what could be the reason of this happening ?

**Comment by Mitchell5200** [comment]
Without Logs this is unable to be diagnosed or fixed, Closing unless the issue is still occurring
