### ISSUE TITLE
Right-click on grass does not give Pebbles

### ISSUE THREAD

**Issue by Raezzur** [AllTheMods/All-the-mods-7-Sky#156]
Hi, I'm playing in multiplayer with a friend hosting and when we right-click the grass it doesn't give us any pebbles. Any recommandations ?

**Comment by enigmaquip** [comment]
Check and make sure all the folders are there. That generally means the server doesn't have the necessary kubejs files

**Comment by Raezzur** [comment]
Even in solo world it does not work. I tried to replace the files, redownload the modpack and it's still the same. V1.0.5 btw

**Comment by asanonisshoku** [comment]
Im seeing the same issue in singleplayer

**Comment by DjinnandTonic087** [comment]
Same issue here. Singleplayer. Fresh download and install today V1.0.5

**Comment by asanonisshoku** [comment]
if anyone needs a temporary workaround the slow method of turning sapling to dirt and sieving that for pebbles works fine.

**Comment by enigmaquip** [comment]
Pushing a new update shortly with fixes in place, keep an eye out for 1.0.6

**Comment by Raezzur** [comment]
Put the fixed files in, works just fine! Thank you.
