### ISSUE TITLE
Start Server Batch file only takes Java 17 unless editited for Java 18

### ISSUE THREAD

**Issue by Goreko** [AllTheMods/All-the-mods-7-Sky#159]
With Java 18 Released and working for Minecraft 1.18 and above, I don't see a reason to not simply use a greater than or equal to instead of a hard equal for version 17. It isn't a super big deal, just a minor gripe after spending a couple of hours following the rabbit hole the first Server install for 1.0.4 and above.

**Comment by Goreko** [comment]
A brief example in the batch file would be to replace == with GEQ, so it takes 17 and 18 versions of Java, and maybe modify the other two lines with "and higher" after Java 17 for letting people know where the issue lies.

Thanks for the wonderfully fun pack btw!

**Comment by nitrog0d** [comment]
It's the default version for Minecraft now, no need to update to 18 unless they do

**Comment by Goreko** [comment]
Understandable, I just happen to do development that tends to require the latest release, so I might be an oddball on the latest Java JDK. Not sure how often people would come across this, might make someone else's life simpler later with just this existing.

Thanks!
