### ISSUE TITLE
No cobalt recipe for Create's crushing weel

### ISSUE THREAD

**Issue by fefocwb** [AllTheMods/All-the-mods-7-Sky#161]
Hello,

I lost a pack of 64 9x compressed raw cobalt ore when I sent it to the create's crushing weel. There is a recipe to have a 9x cobalt but no use on crushing weel but for all other raw ores there is one... This could lead into sittuation like this where you lose ores due no recipe for it.

**Comment by enigmaquip** [comment]
Fixed in 1.0.8
