### ISSUE TITLE
[mod request] Add Extra Cells 2

### ISSUE THREAD

**Issue by motz0815** [AllTheMods/All-the-mods-7-Sky#162]
[Extra Cells 2](https://www.curseforge.com/minecraft/mc-mods/extracells2) is an addon-mod for Applied Energistics 2, which provides the main storage system in this modpack (following the questbook).
It adds goodies like the [ME Ore Dictionary Export Bus](https://ftbwiki.org/ME_Ore_Dictionary_Export_Bus), which is very useful when building automatic ore processing.
The mod also increases limits to how large storage cells can be, with cells [up to 16384k](https://ftbwiki.org/ME_16384k_Storage)

**Comment by Slaymeister** [comment]
This is the current version of this mod, 
[https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork](url)

and this is the suggestion thread. #45
