### ISSUE TITLE
Unable to cast Tin Ingots from Tinker's Smeltery

### ISSUE THREAD

**Issue by melbellrocks** [AllTheMods/All-the-mods-7-Sky#163]
Playing single player on ATM7 Sky v1.0.6 and I am unable to cast tin ingots from the Tinker's Smeltery.  I can cast the blocks just not the ingots.

**Comment by melbellrocks** [comment]
After a pack reload I am now able to cast tin ingots from the smeltery.

**Comment by melbellrocks** [comment]
It comes and goes, and is not limited to tin ingots.

**Comment by PhoenixEvolver** [comment]
Vouch
![2022-09-12_15 36 14](https://user-images.githubusercontent.com/67493734/189770485-c43683ae-fc41-4d4c-a873-9deec4025284.png)

![2022-09-12_15 36 09](https://user-images.githubusercontent.com/67493734/189770458-d7fa0df2-38fa-401a-aba2-a041323994a9.png)

No Tinker's Casting table on both pages of tabs for Constant Ingots.

**Comment by Mitchell5200** [comment]
Confirmed working in 1.1.4, Closing
