### ISSUE TITLE
[ATM7Sky 1.0.6] No smeltery recipe for Constantan Ingot

### ISSUE THREAD

**Issue by trevorjd** [AllTheMods/All-the-mods-7-Sky#167]
I can alloy Constantan and cast blocks but there's no recipe for an ingot. Seems like an oversight to me.

edit: nor Aluminum
eddit: nor Tin
edddit: nor Osmium, nor Steel
eddddit: nor Electrum

**Comment by Mitchell5200** [comment]
Confirmed working in 1.1.4, Closing
