### ISSUE TITLE
The quest for emergency saplings is broken

### ISSUE THREAD

**Issue by Ax3dGaming** [AllTheMods/All-the-mods-7-Sky#168]
The quest for the emergency saplings in broken in ATM 7 To the sky
![image_2022-09-14_154312429](https://user-images.githubusercontent.com/58399906/190170663-a24030e1-a90e-4f7f-9942-86054422b22e.png)

**Comment by enigmaquip** [comment]
That's not the emergency sapling quest, that's the quest telling you where to find the emergency saplings which is this button right here
![image](https://user-images.githubusercontent.com/6134440/191684792-d52aab9d-c959-4031-9b90-667c3aa5d17c.png)
