### ISSUE TITLE
Nexium Emitter recipe is a bit of a time bomb

### ISSUE THREAD

**Issue by AWDoBaun** [AllTheMods/All-the-mods-7-Sky#170]
Using a "Wireless Crafting Terminal".
click "U" while mousing over the terminal.
Scroll to "Nexium Emitter" and click [+] button.
JEI happily moves the Wireless Crafting Terminal you are using out of your inventory into itself.

If you then close the crafting dialog you lose the wireless crafting terminal and any other inventory items it moved into iself.

A better recipe might use the underlying components of the wireless crafting table instead of the table itself, Wireless receiver, Crafting terminal, and Dense energy cell.

![image](https://user-images.githubusercontent.com/12954977/190300122-859f00a2-0697-41e0-87ff-d3553a77013d.png)
instead of 
![image](https://user-images.githubusercontent.com/12954977/190300024-84e6aaa9-f0e6-496a-9abc-cb8a0a4ef3c0.png)

**Comment by andrewsf** [comment]
[Did you report this to AE2? It is an AE2 bug that should get fixed.](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/)

**Comment by AWDoBaun** [comment]
> [Did you report this to AE2? It is an AE2 bug that should get fixed.](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/)

I was under the impression that the nexium emitter recipe was only in ATM and did not exist anywhere else.
As such this use ( abuse ) of this part in this recipe really isn't a significant issue for AE2.
I think I might report it there too because obviously their attempt to control players moving the crafting grid is failing. But it will be a very low priority bug for them because they would never expect anyone to do that. It reminds me of how many times Soaryn has abused mods that pretend to control players from moving things in their inventory.

**Comment by AWDoBaun** [comment]
Hmm the minimum testcase to repro that outside this pack that I can imagine would still involve JEI or equivalent and a mod to add recipes. Cannot do it in vanilla + forge + AE2 because AE2 crafting interfaces do not let you access the vanilla recipe book.

**Comment by andrewsf** [comment]
The bug is not related to the recipe, the bug is that the wireless crafting grid allows moving itself out of the user's inventory while in use.

> I can easily see them passing the buck on this to JEI team too.

While using any Wireless Terminal, try moving a Network Tool around in your inventory, or into the ME storage network. At least for me, that operation is blocked. I don't think JEI is doing that blocking.
