### ISSUE TITLE
Server crashing without warning

### ISSUE THREAD

**Issue by motz0815** [AllTheMods/All-the-mods-7-Sky#173]
Hi there, our server started crashing since we've updated the modpack to 1.0.6.
Prior to that, on 1.0.4, the server never crashed once. 

Crashes happen without anything in the console, log files, or even debug files. The log just ends. (There is also no crash-report)

Maybe there is something wrong with the forge version this modpack version uses? I have really no idea, and I know that this issue won't even help much, but maybe someone finds something more insightful._

**Comment by FroggieNL** [comment]
When does it crash? If your joining the server or starting the server?

You could try a fresh installation downloaded of the curseforge website and copy paste your world into this map.

**Comment by motz0815** [comment]
Just at any time, no special kind of event happened when the server crashes.
For example last time there were several players online atm, no one left or joined recently, but then the server crashed.

I'll try downloading the new files and replacing the world, thanks for the suggestion.

**Comment by Mitchell5200** [comment]
Closing after no further response from poster
