### ISSUE TITLE
Limestone unobtainable

### ISSUE THREAD

**Issue by PrettyTrashX** [AllTheMods/All-the-mods-7-Sky#175]
Limestone, and by extension limestone seeds are seemingly not obtainable by any means.

Aditionally it would be nice if these seeds along with deepslate could be added to the quest book objectives too.

Version: 1.0.4 (not yet checked in newer versions though I saw no mentions of these issues in change logs)

**Comment by enigmaquip** [comment]
Fixed in 1.0.8
