### ISSUE TITLE
Modpack not installing with curseforge

### ISSUE THREAD

**Issue by AlexAuragan** [AllTheMods/All-the-mods-7-Sky#182]
The modpack fails to install using curseforge (v 0.207.1.6337)
WhenI click the install button it fails at "applying patch 2 of 6" then it says "deleting files" then nothing as if I didn't press the install button
I tried downloading the importing the modpack, uninstalling and reinstaling curseforge but same issue. I tried installing another modpack and it's working

**Comment by dkraemer** [comment]
I had the same issue.
Running "Repair Installation" before installing ATM7 fixed it for me.

![image](https://user-images.githubusercontent.com/505091/194452892-4e84a30c-2952-4b72-bd72-b8d76b6d359f.png)

**Comment by randmon** [comment]
> odpack fails to install using curseforge (v 0.207.1.6

Had the same issue, This fixed it for me, thanks!

**Comment by randmon** [comment]
> I had the same issue. Running "Repair Installation" before installing ATM7 fixed it for me.
> 
> ![image](https://user-images.githubusercontent.com/505091/194452892-4e84a30c-2952-4b72-bd72-b8d76b6d359f.png)

Had the same issue, this fixed it for me, thanks!

**Comment by RomanSkokov** [comment]
> У меня была такая же проблема. Я решил ее, запустив «Восстановление установки» перед установкой ATM7.
> 
> ![image](https://user-images.githubusercontent.com/505091/194452892-4e84a30c-2952-4b72-bd72-b8d76b6d359f.png)

И мне тоже помогло с другим модпаком, спасибо, ты мой друууууг!!!
