### ISSUE TITLE
Productive Bees 0.9.1.3 bug - Bees wont leave the hive in the overworld

### ISSUE THREAD

**Issue by Rykee** [AllTheMods/All-the-mods-7-Sky#183]
Hey!

ATM7 to the sky version: 1.0.7

There is a bug in the  0.9.1.3 version of Productive Bees, where the bees won't exit the hives in the overworld even if the hive is hit with a stick. 
Reproduced in single and multiplayer too.
This bug has been fixed in 0.9.1.4

> 1.18.2-0.9.1.4
   -- Fixed bees in overworld not exiting hive

Temp workaround: Transfer hives to other dimension/compact machine.

Could you guys hotfix this?

**Comment by melbellrocks** [comment]
I have also just discovered that they don't seem to produce their output in the overworld even if you use a simulation upgrade.  I was hoping this would work since it stops them needing to exit the hive to work, but nope.

**Comment by enigmaquip** [comment]
Updated in 1.0.8
