### ISSUE TITLE
Water Logged blocks and Fired Crucible turning to unfired when placed.

### ISSUE THREAD

**Issue by Wazzzer** [AllTheMods/All-the-mods-7-Sky#184]
Whenever placing sieves they are automatically water logged which I was willing to live but there are also other issues like this. like when placing silkworms on leaves they turn into water blocks until you re-log and then they transfer to the correct block. also the slab crafting table also is waterlogged when being placed.

The main issue I'm having is also when placing fired crucibles they automatically become unfired crucibles. I've tried placing in creative and I have the same issue.

I'm running this on a server don't know if this is creating an issue, I've downloaded the mod pack today and never played it before.

**Comment by Mitchell5200** [comment]
Please ensure you are on the same pack version as the server

**Comment by Wazzzer** [comment]
> 

turns out i'm a idiot it wasnt the same haha thought it was
