### ISSUE TITLE
Alter any recipe in game with integrated dynamics  

### ISSUE THREAD

**Issue by Ocean5torm** [AllTheMods/All-the-mods-7-Sky#187]
There seems to be a bug with the portable logic programmer. 
It has allowed me to alter the recipes of some items by removing them. 
It does not seem to work on all items and all changes are reset on reloading the world.

Here are the reproduction steps:

1. Open the portable logic programmer to the recipe tab
2. Call up any item you want to alter and put the recipe onto the screen
3. literally click off the items you don't want anymore. 
4. Go try to craft

Sometimes the recipe disappears entirely, other times it is modified. I do not know the reason for this.
I have made spirited Thermo generators from Powah with just dielectric paste. 
I tried to make a block of Netherite only need one ingot but it did not work.
I am on the latest version, if you need any more information I can try to provide it.

![2](https://user-images.githubusercontent.com/36420977/191128742-4404523e-5eef-4db3-ac63-b1ba5b025579.PNG)
![1](https://user-images.githubusercontent.com/36420977/191128842-1718b6b7-b8c2-42d6-bb7b-e33ec125541d.PNG)

**Comment by oly2o6** [comment]
This should be something reported to the respected mod author as we do not believe this to be on our side
