### ISSUE TITLE
New update problem

### ISSUE THREAD

**Issue by GrimzSoul** [AllTheMods/All-the-mods-7-Sky#193]
I updated to the new version of the game and got this crash a couple of times.T

he game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

**Comment by GrimzSoul** [comment]
found the issue to be optifine:(

**Comment by Mitchell5200** [comment]
Heh, it always is, i was gonna ask for the crash log, but you've sorted it now, you can use Rubidium instead for some more FPS.
https://www.curseforge.com/minecraft/mc-mods/rubidium/files/3929515
