### ISSUE TITLE
Oak Sieve quest says you can sieve 9 at a time instead of 25 at a time

### ISSUE THREAD

**Issue by Ryanlie** [AllTheMods/All-the-mods-7-Sky#194]
![2022-09-20_16 54 21](https://user-images.githubusercontent.com/38753510/191228309-ddacbfdc-20d5-49e4-93aa-0ff4f935ab9a.png)

The description of the quest contradicts what the tutorial shows, and what you can do in game. the description should be that you can also sieve blocks 25 at a time and replacing 3x3 with 5x5

**Comment by Ryanlie** [comment]
Fixed in Pull request #195

**Comment by enigmaquip** [comment]
Fixed in 1.0.9
