### ISSUE TITLE
[BUG] There is no Max Limit for AbsorptionAmount

### ISSUE THREAD

**Issue by Mini-kun** [AllTheMods/All-the-mods-7-Sky#198]
It stacks and starts to cause FPS issues which results in the game becoming unplayable. Editing player data to reset it to 0 fixes the issue until it starts to stack up again. Going from 120 FPS to 8 in roughly 20-30 hits

The absorption(after testing) appears to be adding when using a tinker's weapon/tool that has the "laceration" property(Nahuitl and Vibranium)
It is also healing players through the same Lacerating "Tinker" Modifier, that have +X Max Health modifiers on their armor.

**Comment by Mitchell5200** [comment]
Unable to replicate on 1.1.4 as Lacerating in tinkers is just an extra DMG boost, Closing unless this error still occurs
