### ISSUE TITLE
Allthemodium sight not working in Twilight forest

### ISSUE THREAD

**Issue by indulonajones** [AllTheMods/All-the-mods-7-Sky#199]
Hey, I have problem which is described in title. Allthemodium sight is just not working in twilight forest. It is working in my skyblock world, but not in the Forest. Any idea how to fix it?

**Comment by Spikesx** [comment]
Not sure of a fix but i can give you away to get some outside of the twilight. If you go to "The Other" below the world in the deepslate part you can find them there. also the sight is working just fine for me on my server

**Comment by Spongman** [comment]
I'm seeing the same thing. It's _only_ broken in the Twilight Forest. If I place the ore block in the Overworld, Nether, Other or a Creative flatworld, then the sight charm highlights the block as expected, so it's something to do with the Twilight Forest.

**Comment by LarryLava** [comment]
I can confirm, it doesn't work in Twilight forest. Also made a gold sight potion, and didn't work either. 

I'm on version 1.1.0 of the pack, on Mac, no shaders or anything.

**Comment by Mitchell5200** [comment]
Confirmed working on 1.1.4, closing
