### ISSUE TITLE
Connected Textures for most chipped blocks don't work.

### ISSUE THREAD

**Issue by Vallith** [AllTheMods/All-the-mods-7-Sky#204]
Almost every single chipped block that should have connected textures, doesn't. The only ones I have found is some of the Andesite blocks, as well as spruce planks. I imagine the rest of the planks is probably fine too, but for example here is a list of blocks I have tried which connected textures hasn't worked.

End Stone
Netherrack
Basalt
Green Terracotta
Granite
Diorite
Blackstone

**Comment by jeremiahwinsley** [comment]
Tracked here: https://github.com/terrarium-earth/Chipped/issues/142

**Comment by Mitchell5200** [comment]
Mod updated, Closing
