### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by Leclowndu93150** [AllTheMods/All-the-mods-7-Sky#205]
![2022-09-23_20 20 03](https://user-images.githubusercontent.com/73310949/192032415-83c0abd0-6a57-4a5d-aa2b-f6dcb113ea7e.png)

**Comment by enigmaquip** [comment]
While it shows that way in jei... Through my testing soul lava fills into a soul lava bucket, and regular lava into a lava bucket. Have you had a different outcome?

**Comment by Leclowndu93150** [comment]
> 

idk i forgor and stopped the pack sorry
