### ISSUE TITLE
Forbidden & Arcanus: Hephaestus Forge is not working

### ISSUE THREAD

**Issue by violentsushi** [AllTheMods/All-the-mods-7-Sky#214]
Version: 1.0.8

After building base structure, Hephaestus Forge can be created, but cannot be interacted with blacksmith gavel to start the crafting process. The necessary crafting materials was provided to the pedestals, in addition to aureal, soul, blood and experience.

Another problem is that crystal obelisk can be created but does not interact with adding aureal to the forge.

![pic 1](https://i.imgur.com/oJZaobR.jpg)
![pic 2](https://i.imgur.com/EE9yJut.jpg)

Tested same setup in vanilla minecraft with only Forbidden & Arcanus, and everything work just fine. Tested working with Fortune III book in vanilla minecraft.

**Comment by thevortex** [comment]
try updating allthetweaks to 2.0.1 on curseforge now, let me know

**Comment by shawnbyday** [comment]
Is your gavel out of charges? Do you have the correct blocks under the forge/crystals/pedastals?

**Comment by violentsushi** [comment]
I was in creative mode to test it, so the gavel has charges left yes. Since I could open the Hephaestus Forge UI, it means that the correct block for the platform is used.

**Comment by violentsushi** [comment]
Saw a youtuber playing to the sky 7, and they didn't have the same issue I was having. They were playing on 1.0.9. I updated and was still having the same issue, but since it is working for them, I am closing the issue.
