### ISSUE TITLE
Patrick bee fishing is not possible with oceans banned

### ISSUE THREAD

**Issue by AWDoBaun** [AllTheMods/All-the-mods-7-Sky#217]
with the ocean biomes on the banned biomes list in 
https://github.com/AllTheMods/All-the-mods-7-Sky/blob/aec904b25ad1f1b4353086fc67e1bb4b9724f5bd/config/skyblockbuilder/common-config.json5

it is not possible to acquire the patrick bee.

Either:
- Patrick and Starry bees should not be in the pack.
- Oceans should be re-allowed ( my preference, yes starting in an ocean can be painful but not debilitating, starting in mushroom fields can be worse. )  my preference in skyblocks is all biomes and small biomes for diversity.
- Something should be added that lets a user change a biome to an ocean
- Patrick bees should be added to a different biome for fishing ( twilight lakes? )
- Patrick bee should be craftable, say by feeding patrick stars to bumble bees for example.
 

Side note: the economy of feeding a block of ATM stars to a bee to make an ATM bee that needs a block of ATM stars as a flower is broken in comparison to players needing 13 ATM stars to "finish" the pack 
for reference: https://www.youtube.com/watch?v=jrLoynDj1BE

**Comment by enigmaquip** [comment]
Patrick Bee already corrected for next release

**Comment by AWDoBaun** [comment]
I entered this since I did not see another issue for this, nor any fix in the code repository. I look forward to seeing how it was dealt with.

**Comment by enigmaquip** [comment]
#215
![image](https://user-images.githubusercontent.com/6134440/192201435-ec6a9f98-c1af-4efa-a4a0-614c4280da2a.png)

**Comment by AWDoBaun** [comment]
Thanks Enigmaquip. I need to up my github fu and figure out how to search over pull requests. Not sure if the suggestion is welcome, love this recipe and the use of spirit, but the first thing I think of when I see this is it was a missed opportunity to use sea_water_bucket.

**Comment by enigmaquip** [comment]
Damnit, I like it. Consider it done

**Comment by enigmaquip** [comment]
Fixed in 1.0.9
