### ISSUE TITLE
[1.0.7] A single arcane bone meal gives ~900 flowers when clicking on a vanilla tall flower

### ISSUE THREAD

**Issue by thibautvangoethem** [AllTheMods/All-the-mods-7-Sky#222]
No clue if this is intended or not, but using a single arcane bone meal from forbidden & arcanus creates 872 duplicates of any vanilla tall flower (e.g. lilac, sunflower ...). Feel free to close this issue if this was intended.

**Comment by oly2o6** [comment]
not intended but this is something that i would assume is a mod issue? going to close it on our side but feel free to link this to their github
