### ISSUE TITLE
1.0.8 Unattainable Items/Quests

### ISSUE THREAD

**Issue by shawnbyday** [AllTheMods/All-the-mods-7-Sky#224]
Hello,

I believe the following quests are currently impossible:

- Productive Bees/Pepto Beesmol Bee due to Pepto Bismol Comb not being a valid item. The Pepto Bismol Bee currently produces Sugarbag Honeycomb.
- Productive Bees/(Brown/Crimson/Red/Warped) Shroombee due to needing to feed the specified mushroom to a Shroombee which aren't obtainable in any way I've found thus far.
- Ars Nouveau/Amethyst Golem Charm due to needing to find an Amethyst Geode for the Budding Amethyst. I've looked all over for one with no luck yet (Twilight Forest, The End, Alfheim).
- Forbidden and Arcanus/Nipa Plants due to the Nipa Plant islands not spawning anywhere I can find (Twilight Forest, The Void/Overworld, Alfheim).

I will keep looking for solutions, however, I wanted to post this for awareness. I know all of these chapters were just added.

Thanks!

**Comment by enigmaquip** [comment]
All nests have had their biome restrictions removed for skyblock so the 3 regarding that are a moot point.
The Other actually has budding amethyst in the treasure room of the dungeon. 
Shroombee's haven't been fully implemented yet and as such those should be removed.

**Comment by Spikesx** [comment]
on this topic of missing items i can't seem to find yellow orchid

**Comment by enigmaquip** [comment]
you can use the philo stone to cycle through flowers, this includes the yellow orchid

**Comment by Spikesx** [comment]
How when i barly get it to work for the mobs

**Comment by shawnbyday** [comment]
> on this topic of missing items i can't seem to find yellow orchid

It is also available via villager trading.

**Comment by Spikesx** [comment]
> > on this topic of missing items i can't seem to find yellow orchid
> 
> It is also available via villager trading.

Yeah i found away to get them now i just need to get the nipa to finish off that quest tree

**Comment by shawnbyday** [comment]
> All nests have had their biome restrictions removed for skyblock so the 3 regarding that are a moot point. The Other actually has budding amethyst in the treasure room of the dungeon. Shroombee's haven't been fully implemented yet and as such those should be removed.

Removed the bee dependency issue from the issue. Will go look for amethyst here in a bit. Is the Nipa Plant in a chest too by chance?

**Comment by enigmaquip** [comment]
New worldgen in the other will include amethyst geodes as well after the next update. Nipa quest is going away

**Comment by enigmaquip** [comment]
Fixed in 1.0.9

**Comment by Porcy** [comment]
Trying to get a sugarbag bee. Followed the tooltip. Broke hundreds of cocoa pods in a jungle biome. Traded with 2 dozens beekeepers in hope to get the spawn egg. Still no bee. Apparently, the cocoa pods need to be naturally generated for them to have a chance to spawn the bee. This bee is required to get the Choco Bee. Looks like a dead end.
