### ISSUE TITLE
Alchemistry (Diamonds)

### ISSUE THREAD

**Issue by Hpgamer122** [AllTheMods/All-the-mods-7-Sky#225]
Just wanting to check, should 32 graphite be making over a stack of diamonds for alchemistry, because it took half a stack of the graphite then just kept producing over a stack of diamonds. wanting to check if this is a bug or if it should work like this

**Comment by AerosAtar** [comment]
I had something similar happen when generating some ice.

- If I put in _exactly_ enough ingredients for the recipe, it worked as expected.
- If, however, I put in _more_ than enough, as long as at least one stack had enough ingredients remaining for the recipe after the first completion, it would continue indefinitely without consuming any further ingredients.

**Comment by Mitchell5200** [comment]
Confirmed working on 1.1.4, closing
