### ISSUE TITLE
Absorption Hoppers

### ISSUE THREAD

**Issue by Spikesx** [AllTheMods/All-the-mods-7-Sky#227]
I noticed this not sure if it was meant to be like this or not so i thought i post it here to see. The Absorption hoppers don't seem to work that well. I got 5 trying to collect the mystical crops i got planted and they can't pick all them up fast enough plus mystical seeds don't give more seeds in this pack so in the end i lose them do to clear lag.

**Comment by andrewsf** [comment]
That's just how they work. Every machine has rates, and they don't all match up with every possible configuration of every other process.
Feel free to use Vacuumulator, which can be upgraded, or Hopperhocks. Scale up if you need more.

**Comment by Mitchell5200** [comment]
Imo, absorption hoppers suck, Closing
