### ISSUE TITLE
Powah dim cards do not charge items cross dimensionally.

### ISSUE THREAD

**Issue by Aduahawen** [AllTheMods/All-the-mods-7-Sky#229]
When loaded into the player transmitter(Powah) the dimensional card(Powah) does not charge items in the backpack (jetpack, building gadget, etc, etc)in other dimensions. I have tested in Twilight Forest, The nether, The End and The other. It will charge items in the overworld.

Pack version 1.0.8

**Comment by Mitchell5200** [comment]
Main location was likely not chunkloaded, Confirmed working on 1.1.4, closing
