### ISSUE TITLE
Fail to syncronize registry data from server

### ISSUE THREAD

**Issue by TheNexusAho** [AllTheMods/All-the-mods-7-Sky#230]
![Screenshot 2022-09-28 035044](https://user-images.githubusercontent.com/99511079/192669544-eef0198a-b60a-408f-8b86-45ad4405741e.png)

I've an issue with the mods while joining the server. The mod files are exactly the same as you can see. Here is the log. Thank you.

[debug-1.log.gz](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9660771/debug-1.log.gz)

**Comment by bstock84** [comment]
For what it's worth, I just spun up a 1.0.8 server yesterday with 1.0.8 client downloaded from FTB client and everything worked fine. I'd say double check the versions of the client and server.

**Comment by Mitchell5200** [comment]
No further response from poster, Closing
