### ISSUE TITLE
Invalid player data

### ISSUE THREAD

**Issue by incomingnerd** [AllTheMods/All-the-mods-7-Sky#231]
I created my world save prior to version 1.0.8 and was having no problems playing on the latest version... until today. On trying to load my (single player) world I received an "Invalid Player Data" message and got kicked back to the menu.

The relevant portion of the logs read as follows:
```
[14:24:59] [Server thread/ERROR]: Exception caught during firing event: null
	Index: 27
	Listeners:
...
		57: LOWEST
		58: ASM: class de.melanx.skyblockbuilder.EventListener onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.ArrayIndexOutOfBoundsException

[14:24:59] [Server thread/ERROR]: Couldn't place player in world
java.lang.ArrayIndexOutOfBoundsException: null
```

I temporarily disabled the Skyblock Builder mod and on logging into my world was greeted by this:
![Overwritten chunk](https://i.imgur.com/luzPULO.png)

Yes, that was part of my AE system. Is there any way to salvage this and re-enable the mod, or do I just have to cut my losses and start a brand new world? I'd imagine trying to paste the chunks to a new location is going to break a whole lot of stuff (laser io links, functional storage controllers, etc.).

**Comment by incomingnerd** [comment]
Also, if the Skyblock Builder mod is that unstable, can I just keep it permanently disabled? Will this break future updates to the pack?

**Comment by jeremiahwinsley** [comment]
First off for recovery - if you're using Curseforge, it makes a backup of your instance when you upgrade. If you right click on the instance in Curseforge, Open Folder, and then go up two folders, you should see a Backups folder containing the previous version of the instance. You should be able to recover your world from that.

Skyblock Builder is what makes it a skyblock world - so without that, new chunks will probably not be skyblock. Typically works fine but in this instance it seems something got corrupted during the update maybe? Try loading the backup, and if that doesn't work you may want to roll back to the previous version (copy the backup elsewhere first) and see if your save loads on that version.

**Comment by MelanX** [comment]
It's not Skyblock Builder, it's architectury. As you can read here, it's index 27: https://gist.github.com/incomingnerd/95c039b5bb380b7a44cdfd8be93eb7eb#file-2022-09-28-2-log-L929
Then, you go down to number 27 and find `27: ASM: class dev.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V`.

**Comment by incomingnerd** [comment]
> First off for recovery - if you're using Curseforge, it makes a backup of your instance when you upgrade. If you right click on the instance in Curseforge, Open Folder, and then go up two folders, you should see a Backups folder containing the previous version of the instance. You should be able to recover your world from that.
> 
> Skyblock Builder is what makes it a skyblock world - so without that, new chunks will probably not be skyblock. Typically works fine but in this instance it seems something got corrupted during the update maybe? Try loading the backup, and if that doesn't work you may want to roll back to the previous version (copy the backup elsewhere first) and see if your save loads on that version.

The world was not corrupted on upgrade. I was playing the world completely fine on the latest version for several days and over multiple sessions. The backup you mentioned is thus useless as it doesn't contain any of the progress I had made.

**Comment by incomingnerd** [comment]
> It's not Skyblock Builder, it's architectury. As you can read here, it's index 27: https://gist.github.com/incomingnerd/95c039b5bb380b7a44cdfd8be93eb7eb#file-2022-09-28-2-log-L929 Then, you go down to number 27 and find `27: ASM: class dev.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V`.

I'm pretty sure it _is_ related to Skyblock Builder, as disabling the SkyBlock Builder mod allows me to log back into my world completely fine (apart from the destroyed chunk). I have changed nothing except disable Skyblock Builder and its dependents.

**Comment by MelanX** [comment]
I just tell you what the log says.

> Even if it is architectury causing the grief, then Skyblock Builder should probably not default to creating new chunk data on errors.

Sorry that if you remove a mod that this mod can't provide its data anymore. Skyblock Builder needs to add its own chunk generator. This chunk generator is being referenced in the `level.dat` file. Maybe Mojang should store the chunk generator code in the `level.dat` file, then you can remove Skyblock Builder without worrying about your world. Or, as always before changing anything you don't know what it could result in, make a backup :)

**Comment by incomingnerd** [comment]
> I just tell you what the log says.
> 
> > Even if it is architectury causing the grief, then Skyblock Builder should probably not default to creating new chunk data on errors.
> 
> Sorry that if you remove a mod that this mod can't provide its data anymore. Skyblock Builder needs to add its own chunk generator.

Yeah, on closer reading of the logs, it looks like you're right. Also, disabling Skyblock Builder and re-enabling it after the fact does reset the the chunk generator data and breaks worldgen for new chunks, so that's not going to be a viable fix.

I've tagged in the Architectury team to see if they've got any ideas.

**Comment by MelanX** [comment]
> Also, disabling Skyblock Builder and re-enabling it after the fact does reset the the chunk generator data and breaks worldgen for new chunks, so that's not going to be a viable fix.

I think the reference for the chunk generator in `level.dat` was reset from "skyblockbuilder:skyblock" to "minecraft:overworld" because "skyblockbuilder:skyblock" wasn't present. There's no way for me to track if Skyblock Builder was removed temporarily and if this world should be skyblock. You could edit your file by using NBT Explorer. For that, you should check if "skyblockbuilder:skyblock" is the correct chunk generator type by creating a new world and copying the values.

**Comment by Mitchell5200** [comment]
Issue solved, Closing
