### ISSUE TITLE
Immersive Engineering Blaze Powder->Blaze Rod Recipe doesn't work.

### ISSUE THREAD

**Issue by fjgreer** [AllTheMods/All-the-mods-7-Sky#232]
Unsure if this is intended or not, but the recipe is shown in JEI, but the Immersive Engineering Press won't accept blaze powder as an input.

![image](https://user-images.githubusercontent.com/1480421/192889759-2c4715aa-1698-4323-b0a1-15a0ad0bb502.png)

**Comment by Mitchell5200** [comment]
Confirmed working on 1.1.4, closing
