### ISSUE TITLE
Ancient Leaves have no texture

### ISSUE THREAD

**Issue by Werneq** [AllTheMods/All-the-mods-7-Sky#234]
After the update 1.0.9 some "Ancient Leaves" have white textures.

![2022-09-29_01 09 34](https://user-images.githubusercontent.com/47800790/192936810-04b2421c-949f-4327-a7ac-75519c8f7df0.png)

**Comment by Werneq** [comment]
The same problem appear on Demonic Leaves:

![2022-09-29_01 15 17](https://user-images.githubusercontent.com/47800790/192937536-92e34f2a-40ba-4673-886c-7a47759e6341.png)

**Comment by Mitchell5200** [comment]
Confirmed working on 1.1.4, closing
