### ISSUE TITLE
Atm Star 

### ISSUE THREAD

**Issue by Spikesx** [AllTheMods/All-the-mods-7-Sky#237]
Working to get the ATM Star on atm7 sky seems and feels worth less, could you guys give more items to get with it. as of not all i see is getting infinite power which is nice, infinite mana which is night if you are a big botana fan. and a creative spell book for ars which again if you like it youd have most of those glyphs. could you add things like the infinite ME drives the meka fluid tanks or gas tanks something

**Comment by Mitchell5200** [comment]
infinite fluid/gas tanks have been considered, and rejected. Closing
