### ISSUE TITLE
[Bug] [1.0.9] Adding a soul lantern to an Apotheosis Hedge Spider spawner crashes the world

### ISSUE THREAD

**Issue by Joeboon2** [AllTheMods/All-the-mods-7-Sky#238]
Adding a soul lantern to a hedge spider spawner to ignore light levels hard bricks the world. I hard crashed and now am unable to launch my world. Attached is the crash report.

[crash-2022-09-29_17.50.08-server.txt](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9679923/crash-2022-09-29_17.50.08-server.txt)

**Comment by enigmaquip** [comment]
Sadly we missed black listing this when we got the other spider that does the same thing. Only real fix is to edit your world with nbt explored and change the spawner out

**Comment by MorningSage** [comment]
I'm guessing the other spider is the SwarmSpider, lol.  NBT Explorer, here I come!
