### ISSUE TITLE
No way to make Chemlib ingots

### ISSUE THREAD

**Issue by prog-dude** [AllTheMods/All-the-mods-7-Sky#240]
I'm unable to make chemlib ingots. There is no recipe for those in JEI, and when smelting Chemlib dust I get AllTheOres ingots.

When making dust it is only accepting chemlib stuff, and not anything else, so I had to get it from rocks instead. Way slower, but doable.

The Chemlib ingots are needed for Alchemistry reactor casings. So currently I see no way to get deep into Chemlib.

**Comment by jeremiahwinsley** [comment]
If you're on the latest version of the pack, you should be able to use a stonecutter to turn AllTheOres blocks into chemlib blocks, and from there into chemlib ingots.

**Comment by prog-dude** [comment]
Thanks!
