### ISSUE TITLE
Traveller's Logbook (Twilight Forest Patchouli Guide) cannot load

### ISSUE THREAD

**Issue by wrincewind** [AllTheMods/All-the-mods-7-Sky#242]
if you open the Traveller's Logbook, you get the error: 

"Error building entry twilightforest:world/portal. Error while loading entry twilightforest:world/portal page 2. 
Malformed item ID."

i assume the page (https://github.com/TeamTwilight/twilightforest/blob/1.18.x/src/main/resources/data/twilightforest/patchouli_books/guide/en_us/entries/world/portal.json)

is trying to render an item that's been removed, disabled, or otherwise tweaked, but i'm not certain.

**Comment by Mitchell5200** [comment]
Looks like a direct issue in Twilight's page (there's a 0 where there should be an A), and as twilight has stated they will not be backporting any fixes or updates from 1.19 back to 1.18, the 1,18 version is essentially dead. and the Patchouli book seems to not be in the 1.19 version yet either.
Closing
