### ISSUE TITLE
Sieves waterlog

### ISSUE THREAD

**Issue by Hoagie13** [AllTheMods/All-the-mods-7-Sky#243]
I started a new server using Scalacube. However I finally got the server to start in the correct level type but whenever i put down a block that is capable of being waterlogged it becomes waterlogged even with no water sources around, covered and no rain.

**Comment by Mitchell5200** [comment]
Sounds like you have a different client pack version compared to the server, update the client or the server

**Comment by Mitchell5200** [comment]
No further response from poster, Closing
