### ISSUE TITLE
"Sorry, we cant load this project. Missing dependency: 3950762"

### ISSUE THREAD

**Issue by LJLittleman7** [AllTheMods/All-the-mods-7-Sky#244]
Curseforge doesn't seem to work, and pops up with this error. I've tried repairing installation twice and that hasnt worked, and i cant find any other methods of fixing it. Would you be able to help?
![image](https://user-images.githubusercontent.com/114834322/193428268-976b5703-42ec-49f3-8d70-21f5b73a9422.png)

Edit: Resolved, its installable now :)

**Comment by bestbyrush41** [comment]
you are not alone in that one same with me

**Comment by DAmNRelentless** [comment]
Seems to be this [Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis/files/3950762) file, interesting.

**Comment by alex-lougheed4** [comment]
I'm also having this issue^

**Comment by quiddel** [comment]
Sems to apply to older versions as well (I tested it for 1.0.6 and current).

**Comment by twosky2000** [comment]
doesn't even work with ATLauncher
`com.atlauncher.network.DownloadException: https://api.curseforge.com/v1/mods/313970/files/3950762 request wasn't successful: Response{protocol=h2, code=404, message=, url=https://api.curseforge.com/v1/mods/313970/files/3950762}`

**Comment by ChiefArug** [comment]
This should be resolved now, the file (specifically this one https://www.curseforge.com/minecraft/mc-mods/apotheosis/files/3950762) needed some poking in the CF backend

**Comment by LJLittleman7** [comment]
> This should be resolved now, the file (specifically this one https://www.curseforge.com/minecraft/mc-mods/apotheosis/files/3950762) needed some poking in the CF backend

Thanks! Its working now, im assuming that the problem was with apotheosis installing, because it wouldnt pass it, but its working fine now. again, thanks!
