### ISSUE TITLE
Quest Suggestions to change redundant/not required quests from progression

### ISSUE THREAD

**Issue by ixanza** [AllTheMods/All-the-mods-7-Sky#246]
Getting started part 2 has you crafting the pulverizer/enrichment chamber and gets you upgrading your iron furnace. It's clearly intended that the furnace of choice is Iron Furnaces. Once you finish the mekanism/thermal progression line in getting started, the mod's full questline there expects you to craft the mod's furnace to progress further which is very wasteful on resources early on as they're not needed.

There are a few quests where the items requested is not required for the next quests as well which I think should be removed or moved elsewhere. For example the AE2 questline requests you to make an ME chest AND an ME Disk Drive to progress to the ME Disks, you don't need both of them to make your system work. You don't even need an ME controller to get your network up and running, the disk drive quest is more important than the controller

The questline also tells you that you need chargers to make fluix but you get fluix from sieving and the charger is not required. The quest that mentions certus is renewable is also applicable to fluix.

Requiring a certus quartz crystal to start the questline and THEN requiring a seed is also backwards, you already got the seed to make the crystal unless you're in netherite mesh territory.

I think advanced inscribers and circuit etchers should be progressed upon from inscribers quest and not autocrafting, you don't need autocrafting to make advanced inscribers, they only cost iron, diamond, redstone, certus, and wood.

The ME cell quest should be able to accept 1,4,16,64,256k me storage cells and not just look for 1k storage cells especially because the quest before it branches out to telling you about 4,16,64,256k cells.

**Comment by oly2o6** [comment]
all of these other than the controller will be in the next update, thank you for all of the insight!
