### ISSUE TITLE
Intro questline and Tinkers quest need tweaks

### ISSUE THREAD

**Issue by borg286** [AllTheMods/All-the-mods-7-Sky#251]
In the intro players often get into Tinker's Construct to get the Kama to get the leaves. Sadly the Tinker's construct questline is not followable because you force the player to get the "Materials and you" book before getting to the tinkers station quest. To get this book the player must have a book, which requires either leather or a slimeball. Leather requires a farm and the slimeball requires the extreemly tedious task of getting sieves, buckets, and lots of plant matter to make dirt, sieve the dirt for mycelium, use it on dirt for mycelium dirt, wood crucible and more plant matter for water, and then only a chance at getting the brown mushroom block to make a mushroom.  Getting paper is possible but is nowhere near as guided as the rest of the tinkers questline.  You've seemed to make the tinker's construct questline be very hand-holdy, but the "materials and you" quest really feels expert-like and it doesn't really add much.

What you need to do is make the book either auto-given, or an optional sidequest. This will make it flow as the player uses tinkers construct in the intro.

Next, the Scorched bricks to Foundry line should have the "Nether Smelting" quest removed and its rewards placed elsewhere. If players start cooking the Nether Grout and create the scorched basin, table, faucet.. upon getting them then they need to go back and make a bunch of Scorched bricks just to progress the quest line.  The players should already be familiar with cooking Grout at this point. You should just get them to make the Foundry blocks. I'd even reduce the hand-holding altogether for the Foundry and just make a major quest to make the foundry items and increase the rewards, instead of tutoring them on how to make the controller, nether grout, smelting the nether grout. The player already made the smeltery controller by pouring copper over a seared brick. It should be simply a piece of text in the quest that hints to players to use obsidian this time.

**Comment by borg286** [comment]
Also it feels weird to give a reward of "materials and you" book for the quest of getting a "materials and you" book. The player only needs 1. The Tinker's questline nor the player don't really benefit from having 2 of the same book.

**Comment by P0kys** [comment]
1. You don't need either leather or slime ball - there is a recipe that uses Canvas (Straw) from Farmer's Delight.
2. Not sure what's your point there? "Make 16 bricks and get 8-16 extra that are needed for the next quest anyway" seems fine
3. Agree on that one but that's just a slight oversight with this particular modpack as the book is (was?) needed for further crafting

**Comment by borg286** [comment]
For (1) it was non-intuitive.  The current wording points to an "You can also just use the Eccentric Tome that you started with" but we don't start out with one. The quest book didn't seem to count.  JEI doesn't show anything for Eccentric Tome either.  This is likely a carryover from ATM7. I recommend at least changing the hint to point to using a knife and cutting grass.

For (2) My point is that it is easy for players to complete quest items not in the strict order the questline is expecting. In my example I had made the scorched basin/table/drains... as the schorched bricks became available. This meant that if I wanted the rewards for following the questline I had to cook another 32 nether grout. If you instead just go from "Nether Grout" to "Creating the Foundry" and bundled all the intermediate quest rewards into the "Creating the Foundry" then you'd get the same overall goal of the player making a foundry w/o risking the player needing to redo the intermediate quests if they had gotten the hang of it with the Smeltry.

For (3) It is no longer needed to make any of the other books. They all take a raw book instead.

**Comment by oly2o6** [comment]
thank you for all the insight! the Foundry section has been changed to no longer include the quests for the bricks, and the book has been moved to an optional side quest, expect these changes in 1.1.6!
