### ISSUE TITLE
all the stuff in nuclear barrels disappears

### ISSUE THREAD

**Issue by NiklasRichter2222** [AllTheMods/All-the-mods-7-Sky#253]
Every time I log back in, All my nuclear waste as well as my polonium is gone. I store it in those barrels, and they are chunk loaded

**Comment by andrewsf** [comment]
That is the primary purpose of the barrels. The following materials will decay at a rate of 1 mB/t while inside of barrels:

* Nuclear Waste
* Spent Nuclear Waste

You can watch this happen if you look at the barrel.

Polonium should NOT decay, regardless of where you keep it.

**Comment by Mitchell5200** [comment]
Closing
