### ISSUE TITLE
Server Crash on Startup

### ISSUE THREAD

**Issue by xNoVoSx** [AllTheMods/All-the-mods-7-Sky#26]
Server is crashing with the following error:
Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
(i have set the Level-type level-type=skyblockbuilder\:skyblock )
https://pastebin.com/in33KprA

**Comment by xNoVoSx** [comment]
found the problem 

on the curseforge page, it's saying "level-type=skyblockbuilder\:skyblock " but the setting is "level-type=skyblockbuilder\:skyblock"

**Comment by Goldensliv** [comment]
are those not the same lines? I'm having the same issue, but after the crash "level-type=skyblockbuilder:skyblock" is replaced with "level-type=skyblockbuilder\:skyblock"

**Comment by jeremiahwinsley** [comment]
the first one has a space after it - it should be `level-type=skyblockbuilder\:skyblock`, no space

**Comment by Goldensliv** [comment]
Still getting the same error
[https://pastebin.com/uinMxqqn](url)

My server properties:
[https://pastebin.com/HLHt8XYW](url)

**Comment by xNoVoSx** [comment]
Oh, sorry wrong I copied the same type it's level-type=skyblockbuilder\:skyblock but on the mod Wiki it's level-type=skyblockbuilder:skyblock without /
