### ISSUE TITLE
Client won't launch starting 1.0.9

### ISSUE THREAD

**Issue by LordMorketh** [AllTheMods/All-the-mods-7-Sky#262]
Been playing fine up through v1.0.8, but neither 1.0.9 or 1.1.0 will launch. The MC launcher starts, when the ATM load screen would come up, I get nothing. The launch never happens (and I've waited upwards of 20 min.) However, if I try to start the launcher again, it says there is already an instance of minecraft running. I have to close processes in the task manager before I can try again. BTW , I am launching from CurseForge (java edition).

**Comment by Dutchone** [comment]
Currently having the same issue, the moment when I press start in the launcher a Java jdk opens in the background.

I does not start minecraft but takes the ram resources,

Windows 10

**Comment by Jorue23** [comment]
Could you guys try exchanging the allthemods version to the one used in 1.0.8 and see if it launches when using that

**Comment by LordMorketh** [comment]
I'm not quite sure what you are suggesting, but I use CurseForge to launch and to update. When it updates the pack it creates a new instance with the new version (to which I copy/paste my saved game), so I have separate instances for v1.0.8 and 1.0.9 and 1.1.0.  The 1.0.8 version loads fine (I am still playing on it). V 1.0.9 and 1.1.0 do not launch, as described above. If it helps I am playing java edition on Windows 10.

**Comment by Jorue23** [comment]
I'm asking you to click on the three little dots of your 1.0.8 instance then click on open folder. Once that opens up go into the folder called "mods" take the file out of it thats called "allthemods" and then some numbers after it. Open the same folder but for your 1.0.9 instance and search for the mod called "allthemods" in there and delete it and instead put in the file that you took out of the 1.0.8 folder.

**Comment by LordMorketh** [comment]
I'm sorry, but the file you indicated does not exist. In the "mods" folder there is an "AllTheCompressed", an "allthemodium", an "alltheores", and an 'allthetweaks". There is no "allthemods".
However, I took the initiative to swap out the "allthemodium" file, as you indicated, since that was the closest file name to the one you listed. There was no effect. The instance (1.0.9) did not launch.

**Comment by Nextactus** [comment]
I am having this issue as well, and can confirm that switching the "allthemodium" mods from 1.0.8 to either 1.0.9 or 1.0.10 does not work.

**Comment by LordMorketh** [comment]
I finally solved the problem. I ended up having to go into the profile settings on CurseForge and manually update the ForgeModloader version to a newer one. Hope this helps others with the same issue.

**Comment by Mitchell5200** [comment]
Launch Forge setting issue, solved, Closing
