### ISSUE TITLE
Unable to mine any of the other ores with allthemodium metals pickaxes

### ISSUE THREAD

**Issue by NunbearTWITCH** [AllTheMods/All-the-mods-7-Sky#263]
After updating to 1.1.0 the allthemodium/vibranium/unobtainium pickaxes (may just be enchanted ones) will not break any of the other ores.  A basic netherite level tinkers pickaxe does work though.

**Comment by Mitchell5200** [comment]
Do you have the enchant "miners fervor" on your pick, because that's the issue then

**Comment by Mitchell5200** [comment]
No response from poster, Closing
