### ISSUE TITLE
Optifine install crash

### ISSUE THREAD

**Issue by Ticskter** [AllTheMods/All-the-mods-7-Sky#265]
i am attempting to install a shaderpack and when i install OptiFine_1.18.2_HD_U_H7  it will not load to the main menu, i remove Optifine and it loads just fine.

When Optifine is installed i can launch th emod pack via Curse Launcher, then i click play on the Minecraft Launcher and that window disappears and anotherone pops up and after about 20 or 30 seconds the second window disappears and im back to the desk top.

I know optifine works cause i use the same version in another mod pack and all is well.

Any Ideas?

**Comment by AerosAtar** [comment]
Use Rubidium and Oculus instead. Optifine does not work with ATM7Sky.

**Comment by Ticskter** [comment]
OK, i have never heard of these two before. Do i need BOTH or just one or the other, which ever works?

**Comment by AerosAtar** [comment]
You need both, as Oculus is an addon for Rubidium that handles shaders. I would also suggest "Magnesium/Rubidium Extras" for some additional benefits.

**Comment by Ticskter** [comment]
Do these work with other mod packs as well? obviously they would have to be the right game version. if they do i will no longer use Optifine!! It took about 5 minutes for optifine to load the shaders and these three allowed me to load the shaders in like 15 seconds.

Thank you AerosAtar for all the help!!

**Comment by AerosAtar** [comment]
*Potentially* is the best answer anyone can give.They are definitely more compatible than Optifine, at least.
