### ISSUE TITLE
Amethyst bronze seed does not work in cloche

### ISSUE THREAD

**Issue by wally314garcia** [AllTheMods/All-the-mods-7-Sky#266]
Amethyst bronze seeds from Mystical Agriculture do not work in the garden cloche from Immersive Engineering. All the other seeds do so I doubt this is by design. I'm playing ATM 7 To the Sky version 1.1.0.

**Comment by Mitchell5200** [comment]
Wrong Github, Transferred to 7sky

**Comment by wally314garcia** [comment]
Fixed it by adding `'amethyst_bronze',` to the list in the file 

\AlltheMods7TotheSkyatm7sky\kubejs\server_scripts\mod_specific\mysticalagriculture\ma_crops.js

at line 94.

**Comment by Vallith** [comment]
Glad you found a fix to your preferences - and I don't remember off the top of my head what tier farmland Amethyst Bronze Seeds need - but the cloche would need something other than dirt in it for the MA seeds to work depending on what tier. They need the appropriate tier farmland.

**Comment by wally314garcia** [comment]
> Glad you found a fix to your preferences - and I don't remember off the top of my head what tier farmland Amethyst Bronze Seeds need - but the cloche would need something other than dirt in it for the MA seeds to work depending on what tier. They need the appropriate tier farmland.

I did make sure to use the appropriate farmland. Thing is, before adding it to the list, it was not even showing up in JEI as usable in the cloche and when I tried it anyway it did not work. After modifying that file it did work with the tier 3 farmland and up, just like all the other tier 3 seeds.
