### ISSUE TITLE
Cannot load 1.10

### ISSUE THREAD

**Issue by Goreko** [AllTheMods/All-the-mods-7-Sky#272]
After launching from Curse forge and getting to the minecraft loading screen, the game hangs right before finishing the progress bar.

Looking at the latest.log file, it freezes after stating a bunch of invalid frame indexes on sprites from allthetweaks mod.

[latest.log](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9740440/latest.log)

To note: I left it running for 5 hours at this point and it is still stuck on the last line of the log and I've done a fresh install of the modpack both with and without using curseforge.

**Comment by IsXGeo** [comment]
I had this exact issue, went away after a reboot. Give that a shot

**Comment by fefocwb** [comment]
Also, if you have McAfee antivirus it blocks the 1.1.0 to load, disabling it works...

**Comment by Mitchell5200** [comment]
No further comment from poster, Closing
