### ISSUE TITLE
Functional Storage compacting drawers cant compact ore pieces into raw ore

### ISSUE THREAD

**Issue by envy2000** [AllTheMods/All-the-mods-7-Sky#276]
as title says, compacting drawers (for some reason) cant compact ore pieced into their corresponding raw ore

**Comment by Vallith** [comment]
My understanding is that it shouldn't. The compacting drawers are meant to either compact blocks with compressible versions (such as 1x, 2x 3x, etc), or compact resources like redstone, coal, etc, into their block form. A block exists to compact the pieces into the raw ore called the Flux Compactor. :)

**Comment by envy2000** [comment]
I guess im just too used to FTB stoneblock 2, where the compacting drawers do, in fact, compress the ore pieces into regular ore (1.12.2 pack, so no raw ore)

**Comment by Mitchell5200** [comment]
Not intended gameplay function, Closing
