### ISSUE TITLE
List of missing | not working crafting recipes

### ISSUE THREAD

**Issue by lotmy** [AllTheMods/All-the-mods-7-Sky#278]
So i played al little bit and found some missing recipes and some not working.

**Not working:**

1. [ ] _Canopy Bookshelf_ - if crafted after recipe it a normal bookshelf
![grafik](https://user-images.githubusercontent.com/78236232/194916926-303e6794-8e84-4b77-a7a7-055817516b7b.png)

**Missing:**

1. [ ] _Arcane Gilded Darkstone_ - suggestion do it like Gilded Blackstone with Darkstone. Like this 
![grafik](https://user-images.githubusercontent.com/78236232/194918743-77bcc7ce-90d7-4e8f-a92c-90266f70ae96.png)

2. [ ] _Nitro Crystal Seeds_ 
![grafik](https://user-images.githubusercontent.com/78236232/195096241-4f792736-8d28-4624-b0b6-398b70121f61.png)

**Status: 1.1.0**

EDITS:
- Added status
- Added Nitro Crystal Seeds

**Comment by Mitchell5200** [comment]
1, you can use the polymorph button to change the recipe
2, arcane gilded darkstone has no functional uses, therefore no need for recipe
3, Nitro crystal seeds are not meant to exist
