### ISSUE TITLE
Blaze spawners

### ISSUE THREAD

**Issue by MasterBladeX** [AllTheMods/All-the-mods-7-Sky#279]
Apothesis Blaze spawners cause massive ping issues when loading into the chunk. The only solution I have found is to change it to peaceful multiple times sometimes taking just as long as not doing anything since the ping wont let you or wait 3-7 min for the ping to clear up.

**Comment by Mitchell5200** [comment]
alternate idea, don't set your spawner to spawn so fast, and have it on a redstone signal so you can turn it on only when needed.
UserDesign error, Closing
