### ISSUE TITLE
No TerraSteel

### ISSUE THREAD

**Issue by BagiIT** [AllTheMods/All-the-mods-7-Sky#280]
Pack Version 1.1.0

In Botania i tryed to create some TerraSteel and it took a Long time to finish (the particles and all thet was showing) after it finished the items on display dissapeared and i got no terrasteel. 
Is it just me or is it a pack bug??

**Comment by NotPiffany** [comment]
If you didn't have enough mana to finish the craft, the ingredients might have despawned.

**Comment by Mitchell5200** [comment]
No response from poster, likely did not have enough mana in nearby pools, Closing
