### ISSUE TITLE
Affix removing/adding tools in Apotheosis

### ISSUE THREAD

**Issue by Theysaywhatnow** [AllTheMods/All-the-mods-7-Sky#282]
These seem to be completely missing/removed, is this intentional compared to having them in the normal ATM7.

Mucking around with sockets etc. was great fun and a reasonable approach for getting step-height on ATM boots etc.

**Comment by enigmaquip** [comment]
I think you are mistaking memories of ATM6 for the way Apotheosis used to work. There currently is no way with Apotheosis in 1.18.2 to remove or move affixes. That was in the 1.16.5 version and that system is still being revamped by Apoth's dev

**Comment by Theysaywhatnow** [comment]
Huh, mad. Sorry about that then.
Thanks for the rapid response.

**Comment by enigmaquip** [comment]
I've seen some pics of the upcoming update on the dev's discord. The new stuff for affixes looks way different and also way fun. Excited for it's release
