### ISSUE TITLE
Armored Piglich Godmode

### ISSUE THREAD

**Issue by Glitched-Fox-Studios** [AllTheMods/All-the-mods-7-Sky#283]
As per AllTheMods/ATM-7#1410, this same exact issue is happening in my ATM-7 Sky pack. No matter what I do, the armored piglich will not take any 'normal' damage. I am using a fully decked out Unobtainium Sword and I still can't damage them. The only damage I do to them is from the Venom 4 enchant on the sword and even that is only 1 damage per second. With 5000 HP, that is a long time to wait.

**Comment by gtokarz** [comment]
Best weapon to kill him is axe with apotheosis %current health damage, you can 5-6 hit him
![image](https://user-images.githubusercontent.com/12443385/195974291-db8d72b0-3a70-4615-9b64-0ea1aa96f766.png)

**Comment by Glitched-Fox-Studios** [comment]
That doesn't work either. Still absolutely ZERO damage.

**Comment by thevortex** [comment]
you **need** to build a mob farm to deal with the piglich effectively

**Comment by FeedTheChunk** [comment]
Any chance you could elaborate on the "build a mob farm."  I have a mob farm and I still can't kill the Piglichs.

**Comment by gtokarz** [comment]
@FeedTheChunk I have found Dygmy based farm (from ars noveau) the best, the passively generate mob looot based on mobs present in area around their home. 
1) Pick up some Pigliches using any means i.e Quantum Catcher or Mob Imprisonment Tool
2) Close them in cells around Dygmys and name tag them
3) Provide source for Dygmys (you can find more in Ars Noveau book)
4) They will generate loot to chest near their home block
