### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by RedStoneGamed** [AllTheMods/All-the-mods-7-Sky#285]
Hello,
I recently updated all the mods 7 to the skies to 1.1.1 and when the game loads to the loading screen it crashes before I can even get to the main menu. The pack was just working yesterday for pack version 1.1.0 please help.

**Comment by penishamjoe** [comment]
same bro

**Comment by V0ru5** [comment]
Same here

**Comment by chispire** [comment]
Seems the memory usage took a huge leap upward, upto  9 714MB in 1.1.1 on my machine
Edit: 1.1.0 memory usage  tops out at about 7 500MB

**Comment by chispire** [comment]
> Hello, I recently updated all the mods 7 to the skies to 1.1.1 and when the game loads to the loading screen it crashes before I can even get to the main menu. The pack was just working yesterday for pack version 1.1.0 please help.

If you have the RAM, set -Xmx to 8 092MB. Then you´ll get to the loading screen. Seems 1.1.1 is memory hungry.

**Comment by penishamjoe** [comment]
> 

no idea what that means but i got 15.4gb of usable ram if that helps

**Comment by penishamjoe** [comment]
> 

thanks you i think it worked, did have to get my friend to tell me what that means but lol still thanks

**Comment by bethanyrbs** [comment]
I'm having the same issue and I have 16gb memory.

**Comment by bethanyrbs** [comment]
I tried upping the memory to that amount but its not working still

**Comment by Schmetterfliege** [comment]
Same for me.
Takes ages to even start up minecraft with ATM7 Sky, and when trying to create a world... somehere stuck around 10.5gb RAM usage. 
Well, the rest of my computer is used the other 4.something GB...

**Comment by Mitchell5200** [comment]
No further response from poster, closing
