### ISSUE TITLE
Potions Master not highlighting ores

### ISSUE THREAD

**Issue by Coldenor01** [AllTheMods/All-the-mods-7-Sky#290]
I was on live yesterday using a Allthemodium Sight charm, looking for Allthemodium Ores on the Twilight Forest. 
After 10 minutes, i could find some ores but these ores weren't highlighted as they should have been with the charm. I also tried with a basic potion and the result is the same ; ores aren't highlighted.

**Comment by thevortex** [comment]
update the potionsmaster mod to the newest version, the fix is on curseforge but another pack update needs to go out to include it
