### ISSUE TITLE
Crash Upon Launch

### ISSUE THREAD

**Issue by ImTehZink** [AllTheMods/All-the-mods-7-Sky#291]
I have seen multiple threads where people are crashing when trying to launch ATM7 Sky. I am having the same issue, BUT none of the older pack versions work for me either. 

I have tried Java 8, 17, and 19, but no luck there either. 
I have tried through both CurseForge and PolyMC Launchers. (I know PolyMC pulls the .zip from CurseForge anyways)

[crash-2022-10-12_19.29.15-client.txt](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9793401/crash-2022-10-12_19.29.15-client.txt)

If ANYONE has ANY ideas I am all ears! This issue has driven me up a wall for the past week and I just want to enjoy a new skyblock :)

**Comment by CodeMonkeyJeff** [comment]
I have this same issue running it from Overwolf.  From a different issue, I changed the memory usage to 8092 and got it to load.  It's still fairly "fragile" for me, though.

**Comment by Mitchell5200** [comment]
Remove Optifine.

Closing
