### ISSUE TITLE
Crashes when opened with optifine 1.18.2

### ISSUE THREAD

**Issue by Ryaja2** [AllTheMods/All-the-mods-7-Sky#294]
I don't know if I am using the wrong optifine version but whenever I open the mod pack with Optifine 1.18.2 H9 the modpack crashes, here is the crash report.
[crash-2022-10-17_19.20.36-client.txt](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9805630/crash-2022-10-17_19.20.36-client.txt)

**Comment by enigmaquip** [comment]
We don't support optifine. Oculus/Rubidium has been known to work well with our packs
