### ISSUE TITLE
Recipe for stripped logs clashing with decorative blocks recipe

### ISSUE THREAD

**Issue by Dyrannu** [AllTheMods/All-the-mods-7-Sky#295]
Recipe from "absent by design" that turns two stripped logs into two all sided stripped logs doesn't work as it gives the beam from "decorative blocks" instead.

ABD mods recipe either needs removing form JEI or changing so it doesn't clash

**Comment by Mitchell5200** [comment]
Polymorph enables recipe switching, click the pair of arrows when using a vanilla crafting table
Confirmed working on 1.1.4, closing
