### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by Hipkno** [AllTheMods/All-the-mods-7-Sky#296]
With the new 1.1.1 update anytime I join a server or a single player world my cpu maxes out at 100% and playing the game as well as doing anything else on my computer becomes impossible. I’ve tried allocating 10gb of ram and updating java 17 but neither has worked. I redownloaded the 1.1.0 modpack version and everything works perfectly. Any help would be appreciated, thanks

**Comment by Ryan-pelo** [comment]
I have same problem. Did you solve this problem? If so, can you please post what you did? If not, can you reopen the post?

**Comment by Hipkno** [comment]
> I have same problem. Did you solve this problem? If so, can you please post what you did? If not, can you reopen the post?

Allocated more ram. Currently giving it 10gb but you might be able to make it work with 8. Just play around with the amount and see what works on your system. Not sure what was happening before i think my ram config wasn't saving so it wasn't actually using more so I had to double check it.

**Comment by Ryan-pelo** [comment]
Just tried that, worked for me too- thanks! Allocated 16GB but only using 10 at the moment
