### ISSUE TITLE
2 Quests for the same Item

### ISSUE THREAD

**Issue by CodexAdrian** [AllTheMods/All-the-mods-7-Sky#30]
In ATM7 Sky 1.0.0, there are 2 quests for the RFTools Coal generator, one in the getting started tab, and another in the All the power tab.

![image](https://user-images.githubusercontent.com/83074853/184460216-c1a99f91-1671-4e7d-8ade-ab17e49b0257.png)
![image](https://user-images.githubusercontent.com/83074853/184460227-c03e20c8-c545-45a9-85bb-ad100ec2322a.png)

**Comment by CodexAdrian** [comment]
![image](https://user-images.githubusercontent.com/83074853/184461179-cb60fc01-fbca-415f-b3ec-334794e5a8f9.png)
![image](https://user-images.githubusercontent.com/83074853/184461186-a60a8a6f-ed7e-4b69-9b50-3cae2c12d696.png)

Magmatic too

**Comment by CantBeLucifer** [comment]
I don't really see this as an issue? At least it's the same with some things i.e. energy cube in ATM7. Also the all the power tree is more of a reference for power whereas the getting started is supposed to be more of a progression based thing. I think they both have reasons to exist.

Maybe one of them should give no reward?

**Comment by oly2o6** [comment]
I might remove it from one or the other, it’s Mainly because the other tabs are for “completing all the mods” whereas getting started is tutorial based

**Comment by TheBedrockMaster** [comment]
Can be closed.
