### ISSUE TITLE
Energy pipe from pipez does not connect with flux plug from flux network

### ISSUE THREAD

**Issue by Kalex301** [AllTheMods/All-the-mods-7-Sky#303]
As title mentionned, I can't connect those together and I have to utilise mekanism's cable.
It does connect to the flux point tho.

This image is the deffault, cable should connect

![unknown_2022 10 22-21 50](https://user-images.githubusercontent.com/65572160/197359828-c464a3ef-a7bc-41ed-80a5-541ccb92229e.png)

This image is when the cable is "taking" energy from the plug, but I want to add energy, not remove. We can see that the plug connect this time (no change of energy tho)

![unknown_2022 10 22-21 50_1](https://user-images.githubusercontent.com/65572160/197359829-0ac14989-62f5-4e58-84bf-f0304bbb61aa.png)

This image is just here to prove that I didn't disconnect the cable

![unknown_2022 10 22-21 50_2](https://user-images.githubusercontent.com/65572160/197359837-bb627627-4126-4138-8bf1-13a3a131751d.png)

Have a nice day

Kalex

**Comment by Mitchell5200** [comment]
confirmed working, Visual bug, Closing
