### ISSUE TITLE
I cant create a world join my server

### ISSUE THREAD

**Issue by TheGembe** [AllTheMods/All-the-mods-7-Sky#308]
I Started playing on 1.1.0 I enjoyed it  I bout a server to play with my friends on it. then it updated to 1.1.1 I couldn't play it at all. it overclocked my memory and CPU that it crashed when I tried opening it. since the 1.1.2 update I can now open it (still takes a bit) but I cant join the server or create a personal world without it crashing. My other friends have the same issue so I know its not only my computer.

**Comment by Ryan-pelo** [comment]
Same problem. 100% CPU and can't create a world

**Comment by chendar3** [comment]
Same thing here. Figured it might be my save it had trouble loading, but I can't create a new world either so there you go :S

**Comment by Ryan-pelo** [comment]
@chendar3 see issue #296 and check if RAM is your problem. For me, the mod pack instance defaults to 4GB of ram. I had to manually increase it to fix it.

**Comment by chendar3** [comment]
Going up to 8GB seems to have done it, still freezes up for a good minute or so on loading the world, but at least no 100% cpu usage and it eventually loads. Thanks!

**Comment by Ryan-pelo** [comment]
@chendar3 you aren’t alone. My small world takes a little over 3 minutes to load. I suspect there’s another underlying issue but my game works so whatever…

**Comment by Mitchell5200** [comment]
No response from original poster, Closing
