### ISSUE TITLE
1.1.2 Crash Issue

### ISSUE THREAD

**Issue by JayGreen05** [AllTheMods/All-the-mods-7-Sky#309]
I tried to update my version to 1.1.2 and every time I try to load into the game it would crash after I click play from the Minecraft launcher

**Comment by MichaudA89** [comment]
Just tested a fix I caught reading different issues. 
Upgrade your Forge Version to 40.1.84
And increase your ram to 9gb min. I crashed out on 8gb

Hope this helps
