### ISSUE TITLE
AllTheModium Bee not producing with Simulator upgrade

### ISSUE THREAD

**Issue by Tatsu-Kishi** [AllTheMods/All-the-mods-7-Sky#313]
Tested in 1.1.1 and 1.1.2 running on a dedicated Linux server.

Advanced Beehives with 5 allthemodium bees and simulator upgrade won't produce combs.
Removing the simulator upgrade resumes production.

3x3x3 cage with 3 advanced beehives. The laserIo has no extractor cards for testing this.
![image](https://user-images.githubusercontent.com/3016344/197980161-10cd4c96-11be-4888-835f-41b6872e591f.png)

2 Hives with their simulator upgrade removed, 1 with the upgrade installed. The non-simulated hives produce normally.
Also tested with a feeder slab at the entrance instead of the in-world block with no change.

For reference, a cell with the same setup with Ancient Bees and simulator upgrade works without issues.

**Comment by Mitchell5200** [comment]
Confirmed working on 1.1.4, closing
