### ISSUE TITLE
update to 1.13 server crash

### ISSUE THREAD

**Issue by castiron3** [AllTheMods/All-the-mods-7-Sky#316]
server is crashing after the world loads.  Worked fine with 1.11  Crashed  on 1.12 until fixing alchemistry.  Now updated to 1.13 and crashing again. [pastebin](https://pastebin.com/8gqufD6k)

**Comment by jeremiahwinsley** [comment]
Doesn't seem to be much info in that crashlog. You could try increasing the max-tick-time in server.properties and see if that gives it enough time to boot, or if you can send me a copy of the world, I can test it that way.

**Comment by castiron3** [comment]
I ended up trying out what i saw in someone elses post about opening old world and removing the alchemistry machines.  then saved world and updated.  Worked like a charm.  thanks for hitting my back up!
