### ISSUE TITLE
Server crashing when joining on 1.1.3

### ISSUE THREAD

**Issue by Luksor** [AllTheMods/All-the-mods-7-Sky#317]
Hi.

After setting up the server on 1.1.3 (updated from 1.0.9) and joining I'm getting a crash.

The server does not crash if I set it up fresh (without copying my world directory).

Similar issue happened on 1.1.2.

The error is on the bottom of the log:
[server_log.txt](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9882731/server_log.txt)

**Comment by jeremiahwinsley** [comment]
This crash is from this bug: https://github.com/SmashingMods/Alchemistry/issues/254

You need to break Alchemistry machines before updating, and then place them back down after updating.

**Comment by Luksor** [comment]
> This crash is from this bug: [SmashingMods/Alchemistry#254](https://github.com/SmashingMods/Alchemistry/issues/254)
> 
> You need to break Alchemistry machines before updating, and then place them back down after updating.

This fixed the issue. Thanks!
