### ISSUE TITLE
Mycelium Spores Called Ancient Spores in Soul Sand Quest

### ISSUE THREAD

**Issue by R-3-X-Y** [AllTheMods/All-the-mods-7-Sky#32]
The soul sand quest says 'Sand is not only required to get soulsand, it is also required to get the ancient spores to make mycelium!' Instead, it should say 'Sand is not only required to get soul sand, it is also required to get the mycelium spores to make mycelium!' The spores also come from sieving dirt, not sand.

**Comment by oly2o6** [comment]
Crap, I swear they were ancient spores in the past and came from sand right? Unless I’m going crazy, I’ll sort it anyway

**Comment by R-3-X-Y** [comment]
Ye it used to be ancient spores

**Comment by enigmaquip** [comment]
Fixed in 1.0.5
