### ISSUE TITLE
Apotheosis spawner + soul lanntern crashes map

### ISSUE THREAD

**Issue by Keep1xel** [AllTheMods/All-the-mods-7-Sky#325]
Added a soul lantern to a spawner and the save instantly crashed. Everytime the world loads i get the "server closed" error.
Crash report: https://pastebin.com/RwpqxApx

**Comment by enigmaquip** [comment]
See #238 
and also https://github.com/AllTheMods/ATM-7/issues/1570 for directions.
Please also update to a more current version that had the twilight forest spiders blacklisted so this doesn't happen again
