### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by Ricsking** [AllTheMods/All-the-mods-7-Sky#329]
Hi. I really like your modpack :) . and i have some suggestion. I feel kinda cheating the Twilight Forest since dirt is the one of the most rare item on skyblocks. i ssuggest you add Big reactors, Ender IO and galacty craft with extra planets mod. and idk if its able nut optifine too (i have problem with add optifine to this mod). thanks you to upload this mod:)

**Comment by enigmaquip** [comment]
We have a suggestion thread for this. You're also asking for mods that are not on 1.18.2. We don't support Optifine, but suggest you try Oculus instead
