### ISSUE TITLE
LaserIO not transferring power

### ISSUE THREAD

**Issue by linuxmant** [AllTheMods/All-the-mods-7-Sky#330]
After updating to 1.1.4, all LaserIO nodes stopped transferring power from flux points or pipez pipes (energy and universal)
Reloading save or restarting minecraft didn't help.

I tried to create a new creative world for more testing and I got the attached crash log.
[crash-2022-11-04_14.23.24-server.txt](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9942124/crash-2022-11-04_14.23.24-server.txt)

**Comment by proEndreeper** [comment]
It looks like this was an error on Dire's part, he has updated LaserIO to v1.4.5 that should include a fix for this issue. The pack will just need to update at some point, but considering they just updated it a little bit ago, it might be a bit before they update the mods again.

**Comment by linuxmant** [comment]
Thanks, manually updating laserio to 1.4.5 fixes it.
