### ISSUE TITLE
Ring of Arcana in harvest goddess mode destroys crops

### ISSUE THREAD

**Issue by Masasuka** [AllTheMods/All-the-mods-7-Sky#332]
While the ring of arcana is in harvest goddess mode and activated it acts like it's on a pedestal and breaks crops to harvest them.

**Comment by oly2o6** [comment]
this is an activation hotkey that changes the mode, go into your projectE hotkeys and find the one that changes the gem of the ring from red back to green

**Comment by Masasuka** [comment]
I can change it to ring of arcana mode, but the harvest goddess ring grows crops, the ring of arcana with a green core  (harvest goddes mode) grows crops and then breaks them, same as a harvest goddess ring would do if it were on a pedestal. 

Before:
![image](https://user-images.githubusercontent.com/893108/201231875-8ee37ed3-e5f8-483e-bf19-56d275e36e53.png)


After:
![image](https://user-images.githubusercontent.com/893108/201232011-7be3973e-10d6-46df-9bc8-63e890362d44.png)

Notice how it's growing crops, but also breaking them

Harvest goddess band for comparison
![image](https://user-images.githubusercontent.com/893108/201232093-40e84705-aa04-4561-9309-075928c30d60.png)

as you can see, it's growing crops, as expected, but not breaking them, also, as expected as the Harvest goddess band says 'on pedestal grows crops, and harvests'

![image](https://user-images.githubusercontent.com/893108/201232215-ce249456-d54e-471c-997f-be715993a7a3.png)
