### ISSUE TITLE
AE2 - autocrafting (crafting card in Molecular Interface) not working properly in ATM7 Sky 1.1.4

### ISSUE THREAD

**Issue by michaelglinka** [AllTheMods/All-the-mods-7-Sky#335]
In the latest update of ATM7 Sky 1.1.4 the autocrafting card in molecular interface is not functioning properly. I set up a system where I want to have 32 of a specific item and in the previous versions, the system worked well. Now I have to take out the crafting card from the molecular interface and re-insert it for the system to re-do the autocrafting, but it stops once the first batch finishes. 

I thought that maybe it was an issue with channels, so I separated that particular system but i noticed that it is true for all molecular interfaces with crafting card.

**Comment by oly2o6** [comment]
i believe there is a block in lazier ae2 called the requester with the exact functionality you are looking for, with the lag associated with the interface auto stocking, it might be disabled by that mod which adds the better method of doing so, either way (broken or intended) i recommend going for the requester instead
