### ISSUE TITLE
Right clicking does not give pebbles? v1.1.5

### ISSUE THREAD

**Issue by toastonrye** [AllTheMods/All-the-mods-7-Sky#337]
I see older versions of the pack had this issue, it's a fresh server install with no modifications made. I'm looking for a config to change but can't find anything yet.

**Comment by toastonrye** [comment]
It seems like the server is missing kubejs scripts when compared to the client I'm just not sure if I can simply copy the entire kubejs folder over to the server..?

Pebbles work fine in single player, not on my local server.

Edit: Copying over the entire kubejs folder seems to have worked..

**Comment by oly2o6** [comment]
The server scripts were accidently missing in the 1.1.5 server files, thanks for letting us know and we will be uploading a fresh fixed version of the server files only, to curseforge within the hour
