### ISSUE TITLE
Ex: Nihilio after 1.1.5 Update broken

### ISSUE THREAD

**Issue by Snulian** [AllTheMods/All-the-mods-7-Sky#338]
Hey folks,
i dont know if this was intended but after the new Update Ex: Nihilo reverted to and older state i assume, the outputs from the sieving options are completely messed up. (See the images). 

This is on my Server which im hosting online. In Singleplayer it works fine, so i think maybe the Server Pack is messed up?

Uranium and Zinc moved from Sand to Gravel, Platinum as well.
Basalt got removed completely.

Also when u want to convert them into the Raw Ore it gives u the Ex: Nihilo ones not the AllTheOres ones. Cobalt also hasnt got any way to get it now cause u cant get it by sieving.

![2022-11-11_17 22 04](https://user-images.githubusercontent.com/99464102/201385436-9b5a3b77-fdb1-420a-99cc-5d540a896fd3.png)
![2022-11-11_17 22 48](https://user-images.githubusercontent.com/99464102/201385439-90eed479-104a-42a5-8440-23e822ec5404.png)
![2022-11-11_17 22 53](https://user-images.githubusercontent.com/99464102/201385441-544a5590-f0ee-4c3b-bb2c-03d0adc2fca5.png)
![2022-11-11_17 23 05](https://user-images.githubusercontent.com/99464102/201385443-12753140-2bc6-4e41-a05f-4d6c6541224a.png)
![2022-11-11_17 23 14](https://user-images.githubusercontent.com/99464102/201385445-ce9fa724-5223-4171-95c4-62c7d97dad25.png)
![2022-11-11_17 23 44](https://user-images.githubusercontent.com/99464102/201385447-8db5124a-a1f0-4629-aa9e-1cdd88fdb804.png)
![2022-11-11_17 24 00](https://user-images.githubusercontent.com/99464102/201385450-abe15a1b-0f31-4e5f-9a40-343dadedf0ae.png)

**Comment by Snulian** [comment]
So i just looked up the scripts on the client side and they are all there. Then i downloaded the Server-Pack and installed it. The Server Pack is missing most of its scripts.

Client Scripts
![Image1](https://user-images.githubusercontent.com/99464102/201390335-21da7bec-a6f3-4cb0-bd6f-46689a432ea1.PNG)
![Image2](https://user-images.githubusercontent.com/99464102/201390345-61483fa5-957e-483f-8fc4-b3609f78e8c1.PNG)

Server scripts
![Image3](https://user-images.githubusercontent.com/99464102/201390353-8a1c2ddf-8ede-46ca-87a0-c7ba6bcd7205.PNG)
![Image4](https://user-images.githubusercontent.com/99464102/201390357-8edfb3f4-ed05-40b2-840d-505d21d18eab.PNG)

**Comment by oly2o6** [comment]
honestly not sure how this happened, uploading a fixed server script to curseforge now! easy fix for you would be grab those client scripts and put them on your server manually, either works
