### ISSUE TITLE
Framed Block: Do not accepte modded glass anymore

### ISSUE THREAD

**Issue by Elkurion** [AllTheMods/All-the-mods-7-Sky#339]
I updated my serveur a few hours ago from 1.0.9 to 1.1.5 and it seems that framed block don't accepte block that were accepted previously ( chipped glass and other modded glass)

**Comment by oly2o6** [comment]
The server scripts were accidently missing in the 1.1.5 server files, thanks for letting us know and we will be uploading a fresh fixed version of the server files only, to curseforge within the hour

**Comment by Elkurion** [comment]
Updated my server with the fixed files but modded glass still can't be place in framed block. Is it intended?
