### ISSUE TITLE
Server Files not working

### ISSUE THREAD

**Issue by gdharron** [AllTheMods/All-the-mods-7-Sky#35]
When trying to get the server files to boot a server I keep getting fatal errors. I have spent a few hours playing with it even with some of my server staff members and none of us can figure this out. I hope I'm not being an idiot here. 

I start off by getting the server files from the curse forge page then extract them and run the server start bat file. It down loads forge and after a bit I get this error: 

`Unrecognized VM option 'UseZGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Restarting automatically in 10 seconds (press Ctrl + C to cancel)`

Tried changing all kinds of args without any luck. including removing that "UseZGC" and tried enabling the experimental VM options without luck too.

Again I hope I'm not being an ape here, I have hosted MC servers for over a decade and this has me stumped...Thanks

**Comment by jeremiahwinsley** [comment]
You need to use Java 17.

**Comment by Visp9** [comment]
I agree with above, Java 17 solved that.

**Comment by Visp9** [comment]
> You need to use Java 17.

What he said, Java 17 solved it.
