### ISSUE TITLE
1.1.7 server crashing on startup

### ISSUE THREAD

**Issue by mike1000195** [AllTheMods/All-the-mods-7-Sky#358]
hello,

i downloaded the latest 1.1.7 server files and launched the serverstart.bat file. it went through its thing, said server was sucessfully installed, and as its supposed to, automatically started the server. it only gets so far before i get a whole load of java 63 errors (which doesnt make sense considering i have jdk 19 installed, unless i need 17? idk) and the batch file recognizes the crash and goes to restart.

i also tried this on 1.1.6, 1.1.5, and even went back to 1.0.0. all crashes at the same exact spot. funny thing is, is when i remove the "mods" folder from the main server folder, it loads perfectly and i actually get to the point to where it prompts me for the EULA, it doesn't even get to that point when i have the mods folder in the main server folder. im not really sure what to do at this point, but any help would greatly be appreciated. ill attach the log file so you can see whats going on. 

thanks,
Mike

[debug.log](https://github.com/AllTheMods/All-the-mods-7-Sky/files/10095690/debug.log)

**Comment by enigmaquip** [comment]
definitely try downgrading to java17, everything is built against that

**Comment by mike1000195** [comment]
alright cool, ill try jdk 17 and let you know what happens, thanks

**Comment by mike1000195** [comment]
yeah jdk17 worked just fine. thank you!

p.s., would be lovely to have a readme or maybe there was a notice that i missed that stated that you needed jdk17 and not to use 19, maybe on the server file download page or something so this doesnt happen to other people. 

thank you, much love <3
