### ISSUE TITLE
Server crashes on Version 1.1.17 - Reverting Ars Nouveau back to 2.7.9 helped

### ISSUE THREAD

**Issue by thunfisch987** [AllTheMods/All-the-mods-7-Sky#361]
Server crashed with Ars Nouveau 2.8.0 installed (error was something with `invalid stored block length`), reverting back to 2.7.9 helped.
Anyone else having this problem?

**Comment by KaledV99** [comment]
Brother, please give me a hand, I can't open the server, explain to me how you did it?

**Comment by thunfisch987** [comment]
@KaledV99 I have a webserver where i also run my gameservers so i didn't use the server in the zip file, i only extracted the mods and config.
