### ISSUE TITLE
Redstone Arsenal Trojan

### ISSUE THREAD

**Issue by mike1000195** [AllTheMods/All-the-mods-7-Sky#367]
tried to open my client of ATM7 to connect to my server today, and it said i was missing redstone arsenal 6.1.0.8. i downloaded it, and as soon as i downloaded it, windows removed it and said it was a trojan ( i highly doubt that ). i turned off windows defender, downloaded the file, plopped it in the mods, turned windows defender back on, and tried to start the game. it was in the middle of loading all the mods, and bam! it removed it again. So i uninstalled ATM7 through curseforge, and completely reinstalled the modpack. as soon as it finished installing it, it uninstalled it again and said Redstone Arsenal was a virus. i have no idea whats causing this just now, it literally was fine yesterday and i never ran windows update or anything. 

any help?

p.s., its also in the mods folder of the server that is being ran on a seperate computer, and its perfectly fine. it is also on my girlfriends pc right next to mine, and hers is running fine. it seems to just be my computer for some reason.

**Comment by mike1000195** [comment]
EDIT: its literally only version 6.1.0.8. every other version works perfectly file, doesnt get removed. idk what windows' problem is with that version, but its kind of annoying.

**Comment by jeremiahwinsley** [comment]
We don't have Redstone Arsenal in the default pack install, so if nothing else, you can just remove it from the server.

I checked the CoFH discord and it seems like a known false positive.

**Comment by mike1000195** [comment]
yeah i just joined the CoFH discord to try and figure it out, but i cant send a message for 10 minutes or something dumb. 

if RA isnt a default pack install, how did it get in the modpack? Im so confused how it could have gotten in there if it wasnt automatically downloaded

**Comment by jeremiahwinsley** [comment]
Not sure how it got added to your server, but it is not present in current (0.4.34) or earlier versions.

Windows should have a way to unquarantine a file, though I'm not sure exactly where.

**Comment by mike1000195** [comment]
im playing on version 1.1.7

**Comment by mike1000195** [comment]
thats what the server is, at least

**Comment by jeremiahwinsley** [comment]
Oh, you're playing ATM7 Sky, not ATM7. Sky does have Redstone Arsenal, yeah.

**Comment by mike1000195** [comment]
resolved, thank you
