### ISSUE TITLE
Bar on the right side on the screen

### ISSUE THREAD

**Issue by ThiesHD** [AllTheMods/All-the-mods-7-Sky#373]
![image](https://user-images.githubusercontent.com/120607380/207735022-ccf8e6b4-794f-4457-bc71-93c854211def.png) 
It is there and I dont know how to change it.

**Comment by Mitchell5200** [comment]
you have a bunch of quests pinned, head into the quest book and unpin them

**Comment by ThiesHD** [comment]
Thanks man
