### ISSUE TITLE
Game crash when joining the world after upgrading to 1.1.9

### ISSUE THREAD

**Issue by ischon** [AllTheMods/All-the-mods-7-Sky#387]
got the error code -1073741571 when back in the minecraft launcher
just upgraded from 1.1.7 to 1.1.9 after downgrading to 1.1.7 game works once more

are there any logs that i can provide that can help with debugging this error?

**Comment by Talidorn** [comment]
If you are running on AMD...

Open configs -> flywheel-client.toml

change:

backend = "INSTANCING"
to
backend = "OFF"

**Comment by ischon** [comment]
top this helped, thnx
