### ISSUE TITLE
ME Interface for AE2 not showing slots to place terminals

### ISSUE THREAD

**Issue by Micahr81** [AllTheMods/All-the-mods-7-Sky#388]
Using the current 1.1.9 version of the modpack, I have built my crafting CPU and placed the ME Interface with the Assemblers. Accessing the interface, there is no bottom row to place the 9 different patterns. 

![2022-12-31_00 09 06](https://user-images.githubusercontent.com/52228944/210127059-e630f5b3-2d8f-48c8-a0a2-532756cb91e9.png)

**Comment by enigmaquip** [comment]
1.18 and higher of AE2 uses pattern providers for that now, no longer using interfaces
