### ISSUE TITLE
[Functional Storage] Drawers

### ISSUE THREAD

**Issue by Coldenor01** [AllTheMods/All-the-mods-7-Sky#390]
Drawers have an issue since i updated to 1.2.0.
When i try to sneak + left click to take a whole stack of items, there's a 95% chance i don't take any item + the game consider i'm trying to break the drawer.

**Comment by LuBanQAQ** [comment]
Turn off the key occupying "sneak+left" in the settings.

**Comment by uberfuzzy** [comment]
It was squirt gun settings,  which was just added in 1.2.0

**Comment by QFrozenAceQ** [comment]
Ive been clicking on the drawer then clicking on the floor then back on the drawer ... Thought it was intended lol
