### ISSUE TITLE
[Bug] Duping with Barrels

### ISSUE THREAD

**Issue by TomasGnG** [AllTheMods/All-the-mods-7-Sky#40]
You can Shift Rightclick blocks to transport them.
If you do it with Barrels with content the content will duplicate.
I only tested it with Clay, so I dont know if this works with other contents

![image](https://user-images.githubusercontent.com/78899725/184478315-031ce4b2-ba08-4151-ad3b-a2a7b8cb6985.png)
![image](https://user-images.githubusercontent.com/78899725/184478327-22f4caf0-3ab9-4465-b5ca-bdb38de102bb.png)
![image](https://user-images.githubusercontent.com/78899725/184478332-9eb8ce2c-7d72-493e-a8da-14d8c16db43a.png)
![image](https://user-images.githubusercontent.com/78899725/184478341-d0430d06-a44b-4237-9000-e0ca914f7d13.png)
![image](https://user-images.githubusercontent.com/78899725/184478345-f1ad56b5-cc06-4230-afca-dea940c01eba.png)

**Comment by enigmaquip** [comment]
Fixed in v1.0.1.... Barrels should no longer be able to be picked up by carry-on
