### ISSUE TITLE
Vanilla Oak chest are without textures

### ISSUE THREAD

**Issue by Y3llowMagic** [AllTheMods/All-the-mods-7-Sky#401]
When I launch a new game, everything is ok, and then, when I start playing, doing my little island, the time comes to place a chest, but when I do that, the chest is halved, like only the upper part have texture, the bottom part is empty. And then after that my game crashes.

**Comment by jeremiahwinsley** [comment]
This is probably the Flywheel issue with AMD GPUs. You can run `/flywheel backend batching` and this should fix the issue. Or you can edit config/flywheel-client.toml with the game closed and make the same change.

**Comment by Y3llowMagic** [comment]
Thanks it works !
