### ISSUE TITLE
Ex Nihilo's Meshs

### ISSUE THREAD

**Issue by zzpixel04zz** [AllTheMods/All-the-mods-7-Sky#405]
Anything above Diamond mesh's does nothing to increase your odds of find specific resources or even remove lower tier items like flint. Emerald and Netherite mesh's are the same as a Diamond mesh for all resources. Some resources do gain 1 extra percentage, but it is not required or even advantageous to upgrade to the higher tier mesh's.

**Comment by AryanShetty** [comment]
Your comment is mostly true. The netherite mesh adds nothing to most resources, but it does add inferium essence to the crushed netherack loot table.
