### ISSUE TITLE
Crashes upon world startup

### ISSUE THREAD

**Issue by misileasdw** [AllTheMods/All-the-mods-7-Sky#410]
For some reason it's been crashing on starting up my world. It loads into the game, but as soon as I boot my world, the game crashes to launcher. I have backend flywheel turned off, so its not that.

**Comment by Lucasenxx** [comment]
Did you ever find a solution to your problem?

**Comment by misileasdw** [comment]
I have not! I ended up just uninstalling the game. A shame, but not much I coulda done.
