### ISSUE TITLE
AE2 Things crashes the client game

### ISSUE THREAD

**Issue by potpie123** [AllTheMods/All-the-mods-7-Sky#413]
I found out that AE2 Things 1.0.3 beta causes crashing on client side but when updating it to 1.0.5 it fixes the problem. This is the new 1.2.1 update of the server.

**Comment by kreis117** [comment]
It is also occurring in my environment.
I am attaching the crash report just in case.
[crash-2023-02-10_13.11.55-client.txt](https://github.com/AllTheMods/All-the-mods-7-Sky/files/10703690/crash-2023-02-10_13.11.55-client.txt)

**Comment by oly2o6** [comment]
hotfix version 1.2.2 has just released to fix this, sorry for not catching it sooner
