### ISSUE TITLE
Ex Nihilo Barrel recipes are gone

### ISSUE THREAD

**Issue by toruPuchuu** [AllTheMods/All-the-mods-7-Sky#43]
Can no longer make clay block in a barrel, etc. I checked, and there are no Ex Nihilo barrel uses in JEI, except as fuel and such.

**Comment by enigmaquip** [comment]
Are you playing single player or on a server
By chance do you have, and can you upload, a copy of your `debug.log`.... not latest.log, but debug. If you do have one, please upload it to https://mclo.gs/ and share the link here

**Comment by toruPuchuu** [comment]
Single player. There is no debug.log. And it worked last night; I started the game this AM, and the clay automation (@pipes) had stopped working... I'll try restarting with Forge debug enabled.

**Comment by enigmaquip** [comment]
Restart should fix it, thanks for turning on debug, if you happen to have it happen again please let us know

**Comment by toruPuchuu** [comment]
Yes, this has been fixed. Thanks
