### ISSUE TITLE
My game won't open at all

### ISSUE THREAD

**Issue by freshlyNut** [AllTheMods/All-the-mods-7-Sky#449]
Hey guys. I'm new here and not sure if there's a specific format that I need to follow but anyway.

So basically I installed ATM7 Skyblock version through the Curseforge installer, same with all the other modpacks, and every time I try to start a new world it just loads indefinitely or ultimately crashes (not responding) after a short while. I don't understand why it won't load. I have tried deleting and reinstalling and still nothing. I haven't had this problem with any other modpacks, even more system heavy ones. Maybe I'm just doing something wrong? I'm not sure. 

I think my system requirements are enough to play the modpack, I have played ATM8, Dawncraft and other bigger packs so I did not think this would be an issue. 

Any tips for troubleshooting will be appreciated.

**Comment by vXkn6** [comment]
Hi, what do you do for solve that error
