### ISSUE TITLE
[Suggestion]The game starts to get stones, it is recommended to change to holding a stick

### ISSUE THREAD

**Issue by KuroPeach** [AllTheMods/All-the-mods-7-Sky#47]
The game starts to get stones, it is recommended to change to holding a stick. That avoids troubles for later games. 

onEvent('block.right_click', event => {
  if (event.hand != MAIN_HAND) { return; }
  let block = event.block
  if (block.hasTag("minecraft:dirt")) {
      let player = event.player
      if (player.getMainHandItem() == Item.of("minecraft:stick")) {
          let loot = [
              "exnihilosequentia:andesite_pebble",
              "exnihilosequentia:basalt_pebble",
              "exnihilosequentia:blackstone_pebble",
              "exnihilosequentia:diorite_pebble",
              "exnihilosequentia:granite_pebble"
          ]
          random = Math.floor(Math.random() * 2 * loot.length)
          dropItem = Item.of(loot[random] ?? "exnihilosequentia:stone_pebble")
          block.popItemFromFace(dropItem,event.facing)
          //player.addExhaustion(1)
          player.swingArm(event.hand)
      }
  }
})

**Comment by enigmaquip** [comment]
It's fine as it is and won't be changed

**Comment by KuroPeach** [comment]
Empty hands will cause unnecessary stones later in the game. Just like Botania, at least let the player squat down, there is a restriction
