### ISSUE TITLE
Permissions For Derivative

### ISSUE THREAD

**Issue by Codefreak000** [AllTheMods/All-the-mods-7-Sky#483]
Hello, I'm trying to make a derivative of this modpack for my server (I was not able to find any other sure fire way to contact you), I have added a few mods and a kubeJS script and plan to add more as the need/want arises. I am trying to publish a modpack via curseforge to make distribution easier and less of a headache for me and my friends to try and get on the server, however because of the All Rights Reserved Licensing for the modpack they are rejecting it till I receive permission from the ATM Team to proceed. 
![image](https://github.com/AllTheMods/All-the-mods-7-Sky/assets/2480413/027e8ae1-7ea9-4651-a052-1ae1f67aaae7)
I would not be doing a "public" release if they just allowed an unlisted type of distribution of a pack, however given the circumstances this is the best route I have.

**Comment by oly2o6** [comment]
Hello! So due to the way curseforge works, anything uploaded to the site would be in violation of the license, a lot of time, effort and resources went into the creation of this project so at this time I will be denying the request to redistribute.
