### ISSUE TITLE
Osmium Pieces

### ISSUE THREAD

**Issue by DocSenf** [AllTheMods/All-the-mods-7-Sky#5]
Cannot make Raw Osmium.

In Beta 4

![osm1](https://user-images.githubusercontent.com/107649307/175770403-0f255930-60cf-4c35-b564-9334cc9b902d.PNG)
![osm2](https://user-images.githubusercontent.com/107649307/175770404-71197a40-3563-4157-9b80-a565e6093305.PNG)

**Comment by oly2o6** [comment]
fixed
