### ISSUE TITLE
Bugs regarding the mods @IronFurnaces and @FunctionalStorage

### ISSUE THREAD

**Issue by Puddel** [AllTheMods/All-the-mods-7-Sky#62]
A furnace from @IronFurnaces only exports 64 Items into a drawer slot when using auto output and stops outputting anymore (when the drawer has a void upgrade equipped, the items get destroyed even though the limit has not been reached).
![image](https://user-images.githubusercontent.com/37541868/185058260-21687f3b-90be-454b-9bbb-6793ed1ea5a9.png)
![image](https://user-images.githubusercontent.com/37541868/185058305-1f1a2e64-7bcb-4ceb-ade6-f86370cedd85.png)

Another bug: When the furnace from @IronFurnaces auto outputs items into a storage controller which has an empty and locked drawer connected the items will get deleted even without an void upgrade.
![image](https://user-images.githubusercontent.com/37541868/185058922-fbca6709-ba1f-4e55-b02e-c9b1371f1cd4.png)

**Comment by oly2o6** [comment]
I would suggest reporting to is directly to the mod author (would assume iron furnaces at a glance), you can link this thread and if anything can be done on our side, feel free to reopen
