### ISSUE TITLE
Allthemodium/Vibranium duping recipe

### ISSUE THREAD

**Issue by KamiAso** [AllTheMods/All-the-mods-7-Sky#67]
Allthemodium, vibranium and many other metals can be duped by extrding to a rod with 1 ingot and being recycle into 2 ingots by the Arc furnace in immersive engineering.[](url)
![1](https://user-images.githubusercontent.com/25843512/185223462-a0d4aac7-4b39-47eb-b835-00dcf7670905.png)
![2](https://user-images.githubusercontent.com/25843512/185223477-f5f46bcb-5f12-4b25-b35c-65c1e72eb045.png)

**Comment by enigmaquip** [comment]
Recycling disabled in 1.0.4
