### ISSUE TITLE
Duplication bug with bundle and backpack

### ISSUE THREAD

**Issue by KamiAso** [AllTheMods/All-the-mods-7-Sky#68]
Backpacks can be upgraded to store multiple stacks of item in one slot and this can be applied to a empty bundle.
Any items can be inserted in the slot with multiple empty bundles and filled all the bundles at the same time.
Items can be dupped by simply taking out these bundle from the backpack and retrieve multiple stacks of items.

**Comment by enigmaquip** [comment]
Fixed, bundles no longer able to stack inside a backpack
