### ISSUE TITLE
No ingot recipe for Brass block

### ISSUE THREAD

**Issue by PresleyHudson** [AllTheMods/All-the-mods-7-Sky#70]
![image](https://user-images.githubusercontent.com/61676998/185462628-176ee1bd-d00d-463c-a58e-8c0946bfe66a.png)
![image](https://user-images.githubusercontent.com/61676998/185462721-e0b5bc58-2020-40cb-b80e-26a2d24fa05a.png)

**Comment by thevortex** [comment]
update AllTheOres(ATO) https://www.curseforge.com/minecraft/mc-mods/ato/files/3941194 :)

**Comment by enigmaquip** [comment]
Fixed in 1.0.2
