### ISSUE TITLE
Carry on on Mek machines cause them to use 0rf/fe

### ISSUE THREAD

**Issue by 1matto** [AllTheMods/All-the-mods-7-Sky#74]
Watched a youtube vide and saw a bug with the smelter in the video but it could be for other Mek machines too

link to vid:https://www.youtube.com/watch?v=JsWVtihFSx4&ab_channel=Superturtle
issue is at 15:36

**Comment by enigmaquip** [comment]
Blacklisted mek in carryon in 1.0.4
