### ISSUE TITLE
Possible rendering crash caused by Apotheosis item crystals

### ISSUE THREAD

**Issue by ethanc-ec** [AllTheMods/All-the-mods-7-Sky#77]
Was shift clicking several items into a wireless crafting terminal (AE2), but when the new crystal item was clicked, the game crashed. 

[latest.log](https://pastebin.com/EWieQFF6) and [crash-client.txt](https://pastebin.com/K7mg1Zb0) files are pasted into pastebin.

**Comment by enigmaquip** [comment]
related to https://github.com/Shadows-of-Fire/Apotheosis/issues/618

**Comment by Sakreton** [comment]
Just had the same problem

https://github.com/Shadows-of-Fire/Apotheosis/issues/618#issuecomment-1221559958

**Comment by enigmaquip** [comment]
Fix in v1.0.3 with Apoth update
