### ISSUE TITLE
Ex Machines: Flux compactor

### ISSUE THREAD

**Issue by Alsososcar** [AllTheMods/All-the-mods-7-Sky#84]
ore pieces dont go to their stack if it newly went through a cycle which can clog up the machine

**Comment by clarketronics** [comment]
This causes relatively large backups in systems and needs to be fixed, the inventory of the block should "sort" after each process cycle.

**Comment by jeremiahwinsley** [comment]
Tracked here: https://github.com/jeremiahwinsley/ExMachinis/issues/2

**Comment by enigmaquip** [comment]
Fixed in Ex Machinis
