### ISSUE TITLE
No Mekanism ore processing recipe for some of the AllTheOres raw ore blocks

### ISSUE THREAD

**Issue by Gombado** [AllTheMods/All-the-mods-7-Sky#85]
The following blocks cannot be processed by the mekanism enrichment chamber like similiar items like 'Block of Raw Iron' can be:

- Block of Raw Nickel
- Block of Raw Silver
- Block of Raw Aluminum
- Block of Raw Zinc
- Block of Raw platinum

Additionally,
-Enriching (mekanism) Block of Raw cobalt results in a KubeJS Cobalt dust which does not have a smelting recipe
-Missing a recipy for (alltheores) iridium plate in the Immersive Engineering Metal Press (with plate mold)

This seems like a bug/omission so I hope the missing recipes can be added.

**Comment by enigmaquip** [comment]
Fixed in 1.0.5
