### ISSUE TITLE
Tinkers Ingot cast doesnt have a recipe for Osmium Ingot

### ISSUE THREAD

**Issue by memyselfandcj** [AllTheMods/All-the-mods-7-Sky#86]
In newest update 1.0.2 there is no ingot cast recipe for molten osmium. You can still cast it in block form but not the ingot form. Not sure if this in intended or not. After more work tin,lead,nickel,aluminum,uranium, and silver have this issue as well

**Comment by clarketronics** [comment]
Appears to be implemented now
![image](https://user-images.githubusercontent.com/38007037/186752255-4eef205f-8310-4205-8ec8-b90405319e35.png)
