### ISSUE TITLE
[1.0.2] Game crash upon being hit by a shulker bullet (Singleplayer)

### ISSUE THREAD

**Issue by WZ-Wahffle** [AllTheMods/All-the-mods-7-Sky#89]
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_20158_()" because "user" is null

[crash-2022-08-21_12.46.46-server.txt](https://github.com/AllTheMods/ATM-7/files/9388920/crash-2022-08-21_12.46.46-server.txt)

**Comment by Mitchell5200** [comment]
Transferred to atm7 sky

**Comment by enigmaquip** [comment]
Fixed in v1.0.3, Apoth update
