### ISSUE TITLE
Botania Living Wood Quest, Wrong Item

### ISSUE THREAD

**Issue by PresleyHudson** [AllTheMods/All-the-mods-7-Sky#91]
![image](https://user-images.githubusercontent.com/61676998/185803186-479e732e-5987-4b3c-89fe-e8440059787f.png)
![image](https://user-images.githubusercontent.com/61676998/185803215-c81a1b43-c15c-4093-b414-76bbd19ae32b.png)
![image](https://user-images.githubusercontent.com/61676998/185803223-18df41d5-80a1-4d0c-8e1f-bee6c0cb3a39.png)

I assume this is a mistake, the Item for the quest should be "Living wood Log" not "Living Wood"

botania:livingwood_log

**Comment by enigmaquip** [comment]
Fixed in 1.0.5
