### ISSUE TITLE
[1.0.2] Framed compacting drawer from Functional Storage not craftable

### ISSUE THREAD

**Issue by KamiAso** [AllTheMods/All-the-mods-7-Sky#92]
Despite the recipe shows correctly in JEI, framed compacting drawer is not craftable, the crafting result will always be regular compacting drawer
![image](https://user-images.githubusercontent.com/25843512/185879380-5a8b0b1f-1c2b-467a-92e2-c39bbbc9436c.png)
![image](https://user-images.githubusercontent.com/25843512/185879401-45ad97b2-5d39-43e8-95fd-4c6067ac9263.png)

**Comment by enigmaquip** [comment]
Recipe tweaked in 1.0.4
