### ISSUE TITLE
 Game crash due to Applied Energistic 2

### ISSUE THREAD

**Issue by ColdDead** [AllTheMods/All-the-mods-7-Sky#99]
If I want to use the search function of Applied, my game always crashes. I also reinstalled the modpack but still have the problem
[crash-2022-08-23_13.33.04-client.txt](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9402148/crash-2022-08-23_13.33.04-client.txt)

**Comment by Mitchell5200** [comment]
Update to pack version v1.0.3, as this was meant to be fixed there
